#!/bin/bash

##########################################################################
##
##  GitHub: https://github.com/slyfox1186/script-repo
##
##  Forked from: https://github.com/markus-perl/ffmpeg-build-script/
##
##  Target Distro: Ubuntu Focal 20.04.5 ( x86_x64 )
##
##  Purpose: To build FFmpeg from source code with addon development
##           libraries also compiled from source code to ensure the
##           latest in extra functionality.
##
##  CUDA: If the CUDA libraries are not installed (for Geforce cards only)
##        the user will be prompted for the script to install them so that
##        hardware acceleration is enabled when building FFmpeg at the
##        script's end.
##
##  Updated: 02.19.23
##
##  Script Version: 2.22
##
##########################################################################

clear

# VERIFY THE SCRIPT DOES NOT HAVE ROOT ACCESS BEFORE CONTINUING
# THIS CAN CAUSE ISSUES USING THE 'IF WHICH' COMMANDS WHEN RUN AS ROOT
if [ "${EUID}" -lt '1' ]; then
    echo 'You must run this script as WITHOUT root/sudo'
    echo
    exit 1
fi

##
## DEFINE VARIABLES
##

progname="${0:2}"
# Master branch snapshot
ffmpeg_ver='59a9727c241aa50f18e713dbabbdd5cf3d379411'
cuda_ver='12.0 Update 1'
script_ver='2.22'
packages="${PWD}"/packages
workspace="${PWD}"/workspace
install_dir='/usr/bin'
CFLAGS="-I${workspace}"/include
LDFLAGS="-L${workspace}"/lib
LDEXEFLAGS=''
EXTRALIBS='-ldl -lpthread -lm -lz'
cnf_ops=()
nonfree='false'
latest='false'

##
## SET THE AVAILABLE CPU COUNT FOR PARALLEL PROCESSING (SPEEDS UP THE BUILD PROCESS)
##

if [ -f '/proc/cpuinfo' ]; then
    cpus="$(grep -c processor '/proc/cpuinfo')"
else
    cpus="$(nproc --all)"
fi

######################
## DEFINE FUNCTIONS ##
######################

exit_fn()
{
    echo '=============================='
    echo '   The script has finished!   '
    echo '=============================='
    echo
    echo 'Make sure to star this repository to show your support!'
    echo 'https://github.com/slyfox1186/script-repo/'
    echo
    exit 0
}


cleanup_fn()
{
    # PROMPT USER TO CLEAN UP BUILD FILES
    echo
    echo 'Do you want to remove all of the build files?'
    echo '=============================================='
    echo
    echo '[1] Yes'
    echo '[2] No'
    echo
    read -p 'Your choices are (1 or 2): ' clean_ans
    clear

        if [[ "${clean_ans}" -eq '1' ]]; then
            rm -fr "${packages}" "${workspace}"
            exit_fn
        elif [[ "${clean_ans}" -eq '2' ]]; then
            exit_fn
        else
            echo 'Error: Bad user input'
            echo '======================'
            echo
            read -p 'Press enter to try again.'
            clear
            cleanup_fn
        fi
}

ff_ver_fn()
{
    echo
    echo '===================================='
    echo '       FFmpeg Build Complete        '
    echo '===================================='
    echo
    echo '  The binary files can be found in the following locations'
    echo
    echo "  ffmpeg:  ${install_dir}/ffmpeg"
    echo "  ffprobe: ${install_dir}/ffprobe"
    echo "  ffplay:  ${install_dir}/ffplay"
    echo
    echo '================================='
    echo '       FFmpeg'\''s Version       '
    echo '================================='
    echo
    ffmpeg -version
    echo
    read -p 'Press enter to continue.'
    clear
    cleanup_fn
}


make_dir()
{
    remove_dir "${1}"
    if ! mkdir "${1}"; then
        printf "\n Failed to create dir %s" "${1}"
        echo
        exit 1
    fi
}

remove_dir() {
    if [ -d "${1}" ]; then
        rm -r "${1}"
    fi
}

download()
{

    dl_path="${packages}"
    dl_file="${2:-"${1##*/}"}"

    if [[ "${dl_file}" =~ tar. ]]; then
        tdir="${dl_file%.*}"
        tdir="${3:-"${tdir%.*}"}"
    else
        tdir="${3:-"${dl_file%.*}"}"
    fi

    if [ ! -f "${dl_path}/${dl_file}" ]; then
        echo "Downloading ${1} as ${dl_file}"
        curl -Lso "${dl_path}/${dl_file}" "${1}"

        ec="${?}"
        if [ "${ec}" -ne '0' ]; then
            echo
            echo "Failed to download ${1}. Exitcode ${ec}. Retrying in 10 seconds"
            echo
            read -t 10 -p 'Press enter to skip waiting.'
            echo
            curl -Lso "${dl_path}/${dl_file}" "${1}"
        fi

        ec="${?}"
        if [ "${ec}" -ne '0' ]; then
            echo
            echo "Failed to download ${1}. Exitcode ${ec}"
            echo
            exit 1
        fi

        echo 'Download Complete...'
        echo
    else
        echo "${dl_file} has already downloaded."
fi

    make_dir "${dl_path}/${tdir}"

    if [[ "${dl_file}" == *'patch'* ]]; then
        return
    fi

    if [ -n "${3}" ]; then
        if ! tar -xf "${dl_path}/${dl_file}" -C "${dl_path}/${tdir}" &>/dev/null; then
            echo "Failed to extract ${dl_file}"
            echo
            exit 1
        fi
    else
        if ! tar -xf "${dl_path}/${dl_file}" -C "${dl_path}/${tdir}" --strip-components 1 &>/dev/null; then
            echo "Failed to extract ${dl_file}"
            echo
            exit 1
        fi
    fi

    echo "Extracted ${dl_file}"

    cd "${dl_path}/${tdir}" || (
        echo 'Script error!'
        echo
        echo "Unable to cd into: ${tdir}"
        echo
        exit 1
    )

}

error_fn()
{
    echo
    echo 'Please create a support ticket to get assistance fixing errors.'
    echo
    echo 'https://github.com/slyfox1186/script-repo/issues'
    echo
    read -p 'Press enter to exit.'
    echo
    exit 1
}

execute()
{
    echo "$ ${*}"

    output=$("${@}" 2>&1)

    # shellcheck disable=SC2181
    if [ "${?}" -ne '0' ]; then
        echo "${output}"
        echo
        echo "Failed to Execute ${*}" >&2
        echo
        exit 1
    fi
}

# build command function
build()
{
    echo
    echo "building ${1} - version ${2}"
    echo '===================================='

    if [ -f "${packages}/${1}.done" ]; then
        if grep -Fx "${2}" "${packages}/${1}.done" >/dev/null; then
            echo "${1} version ${2} already built. Remove ${packages}/${1}.done lockfile to rebuild it."
            return 1
        elif ${latest}; then
            echo "${1} is outdated and will be rebuilt using version ${2}"
            return 0
        else
            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${packages}/${1}.done lockfile."
            return 1
        fi
    fi

    return 0
}

command_exists()
{
    if ! [[ -x $(command -v "${1}") ]]; then
        return 1
    fi

    return
}

library_exists()
{

    if ! [[ -x "$(pkg-config --exists --print-errors "${1}" 2>&1 >/dev/null)" ]]; then
        return 1
    fi

    return 0
}

# confirm a build has completed function
build_done() { echo "${2}" > "${packages}/${1}.done"; }

verify_binary_type()
{
    if ! command_exists 'file'; then
        return
    fi

    binary_type=$(file "${workspace}"/bin/ffmpeg | sed -n 's/^.*\:\ \(.*$\)/\1/p')
    echo
    case ${binary_type} in
    'Mach-O 64-bit executable arm64')
        echo "Successfully built Apple Silicon (M1) for ${ostype}: ${binary_type}"
         ;;
    *)
          echo "Successfully built binary for ${ostype}: ${binary_type}"
          ;;
    esac
}

# cleanup all files function
cleanup()
{
    remove_dir "${packages}"
    remove_dir "${workspace}"
    echo 'Cleanup finished.'
    echo
}

# function to determine if a package is installed or not
installed() { return $(dpkg-query -W -f '${Status}\n' "${1}" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }

cuda_fail_fn()
{
    clear
    echo 'Error: Unable to locate the required hardware acceleration library: /usr/local/cuda-12.0/bin/'
    error_fn
}

gpu_arch_fn()
{
    echo
    local gpu_ans

    echo 'Tune the build to match your specific Nvidia GPU which will maximize the performance output.'
    echo '============================================================================================'
    echo
    echo 'Please select your GPU'\''s architecture.'
    echo
    echo '[1] Pascal   | Geforce GTX [1030, 1050, 1060, 1070, 1080] GT [1010, Titan Xp, Tesla P40, Tesla P4, Discrete GPU on the NVIDIA Drive PX2]'
    echo '[2] Volta    | Geforce GTX [1180, Titan V] Quadro [GV100] Tesla [V100]'
    echo '[3] Turing   | Geforce GTX [1660 Ti] Geforce RTX [2060, 2070, 2080, Titan] Quadro RTX [4000, 5000, 6000, 8000, T1000/T2000, Tesla T4]'
    echo '[4] Ampere   | Geforce RTX [3050, 3060, 3070, 3080, 3090, A2000, A3000, A4000, A5000, A6000]'
    echo '[5] Lovelace | Geforce RTX [4080, 4090, 6000]'
    echo '[6] Hopper   | GH100'
    echo
    read -p 'Your choices are (1 to 6): ' gpu_ans
    
    if [[ "${gpu_ans}" -eq '1' ]]; then
        gpu_arch='compute_61,code=sm_61'
    elif [[ "${gpu_ans}" -eq '2' ]]; then
        gpu_arch='compute_70,code=sm_70'
    elif [[ "${gpu_ans}" -eq '3' ]]; then
        gpu_arch='compute_75,code=sm_75'
    elif [[ "${gpu_ans}" -eq '4' ]]; then
        gpu_arch='compute_86,code=sm_86'
    elif [[ "${gpu_ans}" -eq '5' ]]; then
        gpu_arch='compute_89,code=sm_89'
    elif [[ "${gpu_ans}" -eq '6' ]]; then
        gpu_arch='compute_90,code=sm_90'
    else
        echo 'Error: Bad user input.'
        echo
        echo 'Press enter to start over.'
        clear
        gpu_arch_fn
    fi
}



# print the options available when manually running the script
usage()
{
    echo "Usage: ${progname} [OPTIONS]"
    echo
    echo 'Options:'
    echo '    -h, --help                                         Display usage information'
    echo '            --version                                    Display version information'
    echo '    -b, --build                                        Starts the build process'
    echo '            --enable-gpl-and-non-free    Enable GPL and non-free codecs    - https://ffmpeg.org/legal.html'
    echo '    -c, --cleanup                                    Remove all working dirs'
    echo '            --latest                                     Build latest version of dependencies if newer available'
    echo '            gpu_arch_fn--full-static                            Build a full static FFmpeg binary (eg. glibc, pthreads etc...) **only Linux**'
    echo '                                                                 Note: Because of the NSS (Name Service Switch), glibc does not recommend static links.'
    echo
}

echo "ffmpeg-build-script v${script_ver}"
echo '======================================'
echo

while ((${#} > 0)); do
    case ${1} in
    -h | --help)
        usage
        exit 0
        ;;
    --version)
        echo "${script_ver}"
        exit 0
        ;;
    -*)
        if [[ "${1}" == '--build' || "${1}" =~ '-b' ]]; then
            bflag='-b'
        fi
        if [[ "${1}" == '--enable-gpl-and-non-free' ]]; then
            cnf_ops+=('--enable-nonfree')
            cnf_ops+=('--enable-gpl')
            nonfree='true'
        fi
        if [[ "${1}" == '--cleanup' || "${1}" =~ '-c' && ! "${1}" =~ '--' ]]; then
            cflag='-c'
            cleanup
        fi
        if [[ "${1}" == '--full-static' ]]; then
            if [[ "${ostype}" == 'darwin'* ]]; then
                echo 'Error: A full static binary can only be built on Linux.'
                echo
                exit 1
            fi
        LDEXEFLAGS='-static'
        fi
        if [[ "${1}" == '--latest' ]]; then
            latest='true'
        fi
        shift
        ;;
    *)
        usage
        echo
        exit 1
        ;;
    esac
done

if [ -z "${bflag}" ]; then
    if [ -z "${cflag}" ]; then
        usage
        echo
        exit 1
    fi
    exit 0
fi

echo "Using ${cpus} processors for parallel processing to speed up the make jobs building speed."
echo

if ${nonfree}; then
    echo 'The script has been configured to run with GPL and non-free codecs enabled'
    echo
fi

if [ -n "${LDEXEFLAGS}" ]; then
    echo 'The script has been configured to run in full static mode.'
    echo
fi

mkdir -p "${packages}"
mkdir -p "${workspace}"

PATH="${workspace}/bin:${PATH}"
export PATH

PKG_CONFIG_PATH="\
/usr/local/lib/x86_64-linux-gnu/pkgconfig:\
/usr/local/lib/pkgconfig:\
/usr/local/share/pkgconfig:\
/usr/lib/x86_64-linux-gnu/pkgconfig:\
/usr/lib/pkgconfig:\
/usr/share/pkgconfig:\
/usr/lib64/pkgconfig\
"
export PKG_CONFIG_PATH

if ! command_exists 'make'; then
    echo 'The '\''make'\'' package is not installed. It is required for this script to run.'
    echo
    exit 1
fi

if ! command_exists 'g++'; then
    echo 'The '\''g++'\'' package is not installed. It is required for this script to run.'
    echo
    exit 1
fi

if ! command_exists 'curl'; then
    echo 'The '\''curl'\'' package is not installed. It is required for this script to run.'
    echo
    exit 1
fi

if ! command_exists 'cargo'; then
    echo 'The '\''cargo'\'' command was not found. rav1e encoder will not be available.'
fi

if ! command_exists 'python3'; then
    echo 'The '\''python3'\'' command was not found. The '\''Lv2'\'' filter and '\''dav1d'\'' decoder will not be available.'
fi

##
## CUDA FUNCTIONS
##

cuda_fn()
{
    clear
    echo 'Pick your current linux distro from the list below:'
    echo
    echo '[1] Debian 10 (x86_x64)'
    echo '[2] Debian 11 (x86_x64)'
    echo '[3] Ubuntu 18.04 (x86_x64)'
    echo '[4] Ubuntu 20.04 (x86_x64)'
    echo '[5] Ubuntu 22.04 (x86_x64)'
    echo '[6] Ubuntu WSL 2 (Windows Subsystem for Linux)'
    echo '[7] Return'
    echo
    read -p 'Your choices are (1 to 7): ' cuda_dist
    clear
    if [[ "${cuda_dist}" -eq '1' ]]; then
        wget --show progress -cqO 'cuda-12-u1.deb' 'https://developer.download.nvidia.com/compute/cuda/12.0.1/local_installers/cuda-repo-debian10-12-0-local_12.0.1-525.85.12-1_amd64.deb'
        sudo dpkg -i 'cuda-12-u1.deb'
        sudo cp /var/cuda-repo-debian10-12-0-local/cuda-*-keyring.gpg '/usr/share/keyrings/'
        sudo add-apt-repository contrib
       elif [[ "${cuda_dist}" -eq '2' ]]; then
        wget --show progress -cqO 'cuda-12-u1.deb' 'https://developer.download.nvidia.com/compute/cuda/12.0.1/local_installers/cuda-repo-debian11-12-0-local_12.0.1-525.85.12-1_amd64.deb'
        sudo dpkg -i 'cuda-12-u1.deb'
        sudo cp /var/cuda-repo-debian11-12-0-local/cuda-*-keyring.gpg '/usr/share/keyrings/'
        sudo add-apt-repository contrib
    elif [[ "${cuda_dist}" -eq '3' ]]; then
        wget --show progress -cq 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin'
        sudo mv 'cuda-ubuntu1804.pin' '/etc/apt/preferences.d/cuda-repository-pin-600'
        wget --show progress -cqO 'cuda-12-u1.deb' 'https://developer.download.nvidia.com/compute/cuda/12.0.0/local_installers/cuda-repo-ubuntu1804-12-0-local_12.0.0-525.60.13-1_amd64.deb'
        sudo dpkg -i 'cuda-12-u1.deb'
        sudo cp /var/cuda-repo-ubuntu1804-12-0-local/cuda-*-keyring.gpg '/usr/share/keyrings/'
    elif [[ "${cuda_dist}" -eq '4' ]]; then
        wget --show progress -cq 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin'
        sudo mv 'cuda-ubuntu2004.pin' '/etc/apt/preferences.d/cuda-repository-pin-600'
        wget --show progress -cqO 'cuda-12-u1.deb' 'https://developer.download.nvidia.com/compute/cuda/12.0.0/local_installers/cuda-repo-ubuntu2004-12-0-local_12.0.0-525.60.13-1_amd64.deb'
        sudo dpkg -i 'cuda-12-u1.deb'
        sudo cp /var/cuda-repo-ubuntu2004-12-0-local/cuda-*-keyring.gpg '/usr/share/keyrings/'
    elif [[ "${cuda_dist}" -eq '5' ]]; then
        wget --show progress -cq 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin'
        sudo mv 'cuda-ubuntu2204.pin' '/etc/apt/preferences.d/cuda-repository-pin-600'
        wget --show progress -cqO 'cuda-12-u1.deb' 'https://developer.download.nvidia.com/compute/cuda/12.0.1/local_installers/cuda-repo-ubuntu2204-12-0-local_12.0.1-525.85.12-1_amd64.deb'
        sudo dpkg -i 'cuda-12-u1.deb'
        sudo cp /var/cuda-repo-ubuntu2204-12-0-local/cuda-*-keyring.gpg '/usr/share/keyrings/'
    elif [[ "${cuda_dist}" -eq '6' ]]; then
        wget --show progress -cq 'https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin'
        sudo mv 'cuda-wsl-ubuntu.pin' '/etc/apt/preferences.d/cuda-repository-pin-600'
        wget --show progress -cqO 'cuda-12-u1.deb' 'https://developer.download.nvidia.com/compute/cuda/12.0.1/local_installers/cuda-repo-wsl-ubuntu-12-0-local_12.0.1-1_amd64.deb'
        sudo dpkg -i 'cuda-12-u1.deb'
        sudo cp /var/cuda-repo-wsl-ubuntu-12-0-local/cuda-*-keyring.gpg '/usr/share/keyrings/'
    elif [[ "${cuda_dist}" -eq '7' ]]; then
        return 0
    fi

    # UPDATE THE APT PACKAGES THEN INSTALL THE CUDA-SDK-TOOLKIT
    sudo apt update
    sudo apt -y install cuda
    
    # REMOVE LEFTOVER DEB FILE
    if [ -f 'cuda-12-u1.deb' ]; then
        sudo rm 'cuda-12-u1.deb'
    fi
    
    # CHECK IF THE CUDA FOLDER EXISTS TO ENSURE IT WAS INSTALLED
    if [ ! -d '/usr/local/cuda-12.0/bin' ]; then
        cuda_fail_fn
    else
        PATH="${PATH}:/usr/local/cuda-12.0/bin"
        export PATH
    fi
}

##
## ADDITIONAL REQUIRED GEFORCE CUDA DEVELOPMENT PACKAGES
##
  
cuda_add_fn()
{
    echo
    echo 'Installing Geforce CUDA Developement APT packages'
    echo '====================================================='

    addons=(autoconf automake build-essential libass-dev libc6 libc6-dev libfdk-aac-dev libfreetype6-dev libmp3lame-dev libnuma1 libnuma-dev libtheora-dev libtool libvorbis-dev pkg-config texinfo unzip wget yasm zlib1g-dev)

    for pkg in ${addons[@]}
    do
        if ! installed "${pkg}"; then
            missing_pkgs+=" ${pkg}"
        fi
    done

    if [ -n "${missing_pkgs}" ]; then
        for pkg in "${missing_pkgs}"
        do
            sudo apt install ${pkg}
        done
        echo 'The Geforce CUDA Developement Libraries were successfully installed'
        echo '======================================================================='
    else
        echo 'The Geforce CUDA Dev Libraries are already installed'
        echo '========================================================'
    fi
    sleep 3
    echo
}

##
## INSTALL CUDA
##

if ! which 'nvcc' &>/dev/null ; then
    echo
    echo 'You don'\''t have the cuda-sdk-toolkit installed OR you don'\''t have it in your PATH variable.'
    echo
    echo 'Do you want to install it and/or add it to your PATH?'
    echo
    echo '[1] Install it and add it to my PATH'
    echo '[2] Just add it to my PATH'
    echo '[3] Don'\''t do either and continue the build'
    echo
    read -p 'Your choices are (1 to 3): ' cuda_ans
    echo
    if [[ "${cuda_ans}" -eq '1' ]]; then
        cuda_fn
        cuda_add_fn
    elif [[ "${cuda_ans}" -eq '2' ]]; then
        if [ -d '/usr/local/cuda-12.0/bin' ]; then
            PATH="${PATH}:/usr/local/cuda-12.0/bin"
            export PATH
        else
            echo 'The script was unable to add it to your $PATH because a required folder is missing: /usr/local/cuda-12.0/bin'
            echo
            read -p 'Press enter to continue the build.'
            echo
        fi
    elif [[ "${cuda_ans}" -eq '3' ]]; then
        echo
    else
        clear
        echo 'Error: Bad user input!'
        error_fn
    fi
else
    echo
    echo "The cuda-sdk-toolkit \"v${cuda_ver}\" is already up to date."
fi

##
## BUILD TOOLS
##

if build 'giflib' '5.2.1'; then
    download 'https://netcologne.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz'
    cd "${packages}"/giflib-5.2.1 || exit 1
    #multicore build disabled for this library
    execute make
    execute make PREFIX="${workspace}" install
    build_done 'giflib' '5.2.1'
fi

if build 'pkg-config' '0.29.2'; then
    download 'https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz'
    execute ./configure --silent --prefix="${workspace}" --with-pc-path="${workspace}"/lib/pkgconfig --with-internal-glib
    execute make "-j${cpus}"
    execute make install
    build_done 'pkg-config' '0.29.2'
fi

if build 'yasm' '1.3.0'; then
    download 'https://github.com/yasm/yasm/releases/download/v1.3.0/yasm-1.3.0.tar.gz'
    execute ./configure --prefix="${workspace}"
    execute make "-j${cpus}"
    execute make install
    build_done 'yasm' '1.3.0'
fi

if build 'nasm' '2.16.01'; then
    download 'https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/nasm-2.16.01.tar.xz'
    execute ./configure --prefix="${workspace}" --disable-shared --enable-static
    execute make "-j${cpus}"
    execute make install
    build_done 'nasm' '2.16.01'
fi

if build 'zlib' '1.2.13'; then
    download 'https://zlib.net/fossils/zlib-1.2.13.tar.gz'
    execute ./configure --static --prefix="${workspace}"
    execute make "-j${cpus}"
    execute make install
    build_done 'zlib' '1.2.13'
fi

if build 'm4' '1.4.19'; then
    download 'https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz'
    execute ./configure --prefix="${workspace}"
    execute make "-j${cpus}"
    execute make install
    build_done 'm4' '1.4.19'
fi

if build 'autoconf' '2.71'; then
    download 'https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.xz'
    execute ./configure --prefix="${workspace}"
    execute make "-j${cpus}"
    execute make install
    build_done 'autoconf' '2.71'
fi

if build 'automake' '1.16.5'; then
    download 'https://ftp.gnu.org/gnu/automake/automake-1.16.5.tar.xz'
    execute ./configure --prefix="${workspace}"
    execute make "-j${cpus}"
    execute make install
    build_done 'automake' '1.16.5'
fi

if build 'libtool' '2.4.7'; then
    download 'https://mirror.vern.cc/gnu/libtool/libtool-2.4.7.tar.xz'
    execute ./configure --prefix="${workspace}" --enable-static --disable-shared
    execute make "-j${cpus}"
    execute make install
    build_done 'libtool' '2.4.7'
fi

if ${nonfree}; then
    if build 'openssl' '1.1.1s'; then
        download 'https://www.openssl.org/source/openssl-1.1.1s.tar.gz'
        execute ./config --prefix="${workspace}" --openssldir="${workspace}" \
            --with-zlib-include="${workspace}"/include/ --with-zlib-lib="${workspace}"/lib no-shared zlib
        execute make "-j${cpus}"
        execute make install_sw
        build_done 'openssl' '1.1.1s'
    fi
    cnf_ops+=('--enable-openssl')
else
    if build 'gmp' '6.2.1'; then
        download 'https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.xz'
        execute ./configure --prefix="${workspace}" --disable-shared --enable-static
        execute make "-j${cpus}"
        execute make install
        build_done 'gmp' '6.2.1'
    fi

    if build 'nettle' '3.8.1'; then
        download 'https://ftp.gnu.org/gnu/nettle/nettle-3.8.1.tar.gz'
        execute ./configure --prefix="${workspace}" --disable-shared --enable-static --disable-openssl \
            --disable-documentation --libdir="${workspace}"/lib CPPFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"
        execute make "-j${cpus}"
        execute make install
        build_done 'nettle' '3.8.1'
    fi

    if build 'gnutls' '3.7.8'; then
        download 'https://www.gnupg.org/ftp/gcrypt/gnutls/v3.7/gnutls-3.7.8.tar.xz'
        execute ./configure --prefix="${workspace}" --disable-shared --enable-static --disable-doc --disable-tools \
            --disable-cxx --disable-tests --disable-gtk-doc-html --disable-libdane --disable-nls --enable-local-libopts \
            --disable-guile --with-included-libtasn1 --with-included-unistring --without-p11-kit CPPFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"
        execute make "-j${cpus}"
        execute make install
        build_done 'gnutls' '3.7.8'
    fi
    cnf_ops+=('--enable-gmp' '--enable-gnutls')
fi

if build 'cmake' '3.25.2'; then
    download 'https://github.com/Kitware/CMake/releases/download/v3.25.2/cmake-3.25.2.tar.gz'
    execute ./configure --prefix="${workspace}" --parallel="${cpus}" -- -DCMAKE_USE_OPENSSL='OFF'
    execute make "-j${cpus}"
    execute make install
    build_done 'cmake' '3.25.2'
fi

##
## video libraries
##

if command_exists 'python3'; then
    # dav1d needs meson and ninja along with nasm to be built
    if command_exists 'pip3'; then
        # meson and ninja can be installed via pip3
        execute pip3 install pip setuptools --quiet --upgrade --no-cache-dir --disable-pip-version-check
        for r in meson ninja
        do
            if ! command_exists ${r}; then
                execute pip3 install ${r} --quiet --upgrade --no-cache-dir --disable-pip-version-check
            fi
            export PATH="${PATH}:${HOME}/Library/Python/3.9/bin"
        done
    fi
    if command_exists 'meson'; then
        if build 'dav1d' '77b3955'; then
            download 'https://code.videolan.org/videolan/dav1d/-/archive/77b3955537c716acbbdf4bfc46ec2f6b0ccd683a/dav1d-77b3955537c716acbbdf4bfc46ec2f6b0ccd683a.tar.gz'
            make_dir build
            execute meson build --prefix="${workspace}" --buildtype='release' --default-library='static' --libdir="${workspace}"/lib
            execute ninja -C build
            execute ninja -C build install
            build_done 'dav1d' '77b3955'
        fi
        cnf_ops+=('--enable-libdav1d')
    fi
fi

if build 'svtav1' 'd5e1e2a'; then
    # Last known working commit which passed CI Tests from HEAD branch
    download 'https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/d5e1e2a586020854733f6b0806064d0c900c88d2/SVT-AV1-d5e1e2a586020854733f6b0806064d0c900c88d2.tar.gz' 'svtav1-d5e1e2a.tar.gz'
    cd "${packages}"/svtav1-d5e1e2a//Build/linux || exit 1
    execute cmake -DCMAKE_INSTALL_PREFIX="${workspace}" -DENABLE_SHARED='OFF' -DBUILD_SHARED_LIBS='OFF' ../.. -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE='Release'
    execute make "-j${cpus}"
    execute make install
    execute cp 'SvtAv1Enc.pc' "${workspace}"/lib/pkgconfig/
    execute cp 'SvtAv1Dec.pc' "${workspace}"/lib/pkgconfig/
    build_done 'svtav1' 'd5e1e2a'
    fi
    cnf_ops+=('--enable-libsvtav1')

if command_exists 'cargo'; then
    if build 'rav1e' '0.6.3'; then
        execute cargo install --version '0.9.14+cargo-0.66' cargo-c
        download 'https://github.com/xiph/rav1e/archive/refs/tags/v0.6.3.tar.gz'
        execute cargo cinstall --prefix="${workspace}" --library-type='staticlib' --crt-static --release
        build_done 'rav1e' '0.6.3'
    fi
    cnf_ops+=('--enable-librav1e')
fi

if ${nonfree}; then

    if build 'x264' 'eaa68fa'; then
        download 'https://code.videolan.org/videolan/x264/-/archive/eaa68fad9e5d201d42fde51665f2d137ae96baf0/x264-eaa68fad9e5d201d42fde51665f2d137ae96baf0.tar.gz' 'x264-eaa68fa.tar.gz'
        cd "${packages}"/x264-eaa68fa || exit 1
        execute ./configure --prefix="${workspace}" --enable-static --enable-pic CXXFLAGS="-fPIC ${CXXFLAGS}"
        execute make "-j${cpus}"
        execute make install
        execute make install-lib-static
        build_done 'x264' 'eaa68fa'
    fi
    cnf_ops+=('--enable-libx264')
fi

if ${nonfree}; then

    # When ffmpeg is built it requires the x265 binaries to have the libnuma-dev apt package already installed.
    find_libnuma="$(sudo find /usr/ -name 'libnuma.so')"
    if [ -z "${find_libnuma}" ]; then
        echo '$ installing the required apt package libnuma-dev'
        echo
        sudo apt -y install libnuma-dev
        echo
    fi

    if build 'x265' '3.5'; then
        # download 'https://github.com/videolan/x265/archive/refs/tags/3.4.tar.gz' 'x265-3.4.tar.gz'
        git clone -q 'https://bitbucket.org/multicoreware/x265_git.git' "${packages}/x265-3.5"
        cd "${packages}/x265-3.5/build/linux" || exit 1
        rm -fr {8,10,12}bit 2>/dev/null
        mkdir -p {8,10,12}bit
        cd '12bit' || exit 1
        echo '$ making 12bit binaries'
        execute cmake ../../../source -DCMAKE_INSTALL_PREFIX="${workspace}" -DENABLE_SHARED='OFF' -DBUILD_SHARED_LIBS='OFF' \
            -DHIGH_BIT_DEPTH='ON' -DENABLE_HDR10_PLUS='ON' -DEXPORT_C_API='OFF' -DENABLE_CLI='OFF' -DMAIN12='ON'
        execute make "-j${cpus}"
        echo '$ making 10bit binaries'
        cd ../'10bit' || exit 1
        execute cmake ../../../source -DCMAKE_INSTALL_PREFIX="${workspace}" -DENABLE_SHARED='OFF' \
            -DBUILD_SHARED_LIBS='OFF' -DHIGH_BIT_DEPTH='ON' -DENABLE_HDR10_PLUS='ON' -DEXPORT_C_API='OFF' -DENABLE_CLI='OFF'
        execute make "-j${cpus}"
        echo '$ making 8bit binaries'
        cd ../'8bit' || exit 1
        ln -sf ../'10bit/libx265.a' 'libx265_main10.a'
        ln -sf ../'12bit/libx265.a' 'libx265_main12.a'
        execute cmake ../../../'source' -DCMAKE_INSTALL_PREFIX="${workspace}" -DENABLE_SHARED='OFF' \
            -DBUILD_SHARED_LIBS='OFF' -DEXTRA_LIB='x265_main10.a;x265_main12.a;-ldl' -DEXTRA_LINK_FLAGS='-L.' -DLINKED_10BIT='ON' -DLINKED_12BIT='ON'
        execute make "-j${cpus}"

        mv 'libx265.a' 'libx265_main.a'

        execute ar -M <<EOF
CREATE libx265.a
ADDLIB libx265_main.a
ADDLIB libx265_main10.a
ADDLIB libx265_main12.a
SAVE
END
EOF
        execute make install

        if [ -n "${LDEXEFLAGS}" ]; then
            sed -i.backup 's/-lgcc_s/-lgcc_eh/g' "${workspace}"/lib/pkgconfig/x265.pc
        fi

        build_done 'x265' '3.5'
    fi
    cnf_ops+=('--enable-libx265')
fi

if build 'libvpx' '1.12.0'; then
    download 'https://github.com/webmproject/libvpx/archive/refs/tags/v1.12.0.tar.gz' 'libvpx-1.12.0.tar.gz'
    execute ./configure --prefix="${workspace}" --disable-unit-tests --disable-shared --disable-examples --as='yasm'
    execute make "-j${cpus}"
    execute make install
    build_done 'libvpx' '1.12.0'
fi
cnf_ops+=('--enable-libvpx')

if ${nonfree}; then
    if build 'xvidcore' '1.3.7'; then
        download 'https://downloads.xvid.com/downloads/xvidcore-1.3.7.tar.bz2'
        cd 'build/generic' || exit 1
        execute ./configure --prefix="${workspace}" --disable-shared --enable-static
        execute make "-j${cpus}"
        execute make install

        if [[ -f "${workspace}"/lib/libxvidcore.4.dylib ]]; then
            execute rm "${workspace}"/lib/libxvidcore.4.dylib
        fi

        if [[ -f "${workspace}"/lib/libxvidcore.so ]]; then
            execute rm "${workspace}"/lib/libxvidcore.so*
        fi

        build_done 'xvidcore' '1.3.7'
    fi
    cnf_ops+=('--enable-libxvid')
fi

if ${nonfree}; then
    if build 'vid_stab' '1.1.0'; then
        download 'https://github.com/georgmartius/vid.stab/archive/v1.1.0.tar.gz' 'vid.stab-1.1.0.tar.gz'
        execute cmake -DBUILD_SHARED_LIBS='OFF' -DCMAKE_INSTALL_PREFIX="${workspace}" -DUSE_OMP='OFF' -DENABLE_SHARED='OFF' .
        execute make
        execute make install
        build_done 'vid_stab' '1.1.0'
    fi
    cnf_ops+=('--enable-libvidstab')
fi

if build 'av1' '7be63ce'; then
  # libaom bcfe6fb == v3.5.0
    download 'https://aomedia.googlesource.com/aom/+archive/7be63cef996e6b09c0bfa0057334a5cba5d027c8.tar.gz' 'av1.tar.gz' 'av1'
    make_dir "${packages}/aom_build"
    cd "${packages}"/aom_build || exit 1
    execute cmake -DENABLE_TESTS='0' -DENABLE_EXAMPLES='0' -DCMAKE_INSTALL_PREFIX="${workspace}" -DCMAKE_INSTALL_LIBDIR='lib' "${packages}"/av1
    execute make "-j${cpus}"
    execute make install
    build_done 'av1' '7be63ce'
fi
cnf_ops+=('--enable-libaom')

if build 'zimg' '3.0.4'; then
    download 'https://github.com/sekrit-twc/zimg/archive/refs/tags/release-3.0.4.tar.gz' 'zimg-3.0.4.tar.gz' 'zimg'
    cd 'zimg-release-3.0.4' || exit 1
    execute "${workspace}"/bin/libtoolize -i -f -q
    execute ./autogen.sh --prefix="${workspace}"
    execute ./configure --prefix="${workspace}" --enable-static --disable-shared
    execute make "-j${cpus}"
    execute make install
    build_done 'zimg' '3.0.4'
fi
cnf_ops+=('--enable-libzimg')

##
## AUDIO LIBRARIES
##

if command_exists 'python3'; then
    if command_exists 'meson'; then
        if build 'lv2' '1.18.10'; then
            download 'https://lv2plug.in/spec/lv2-1.18.10.tar.xz' 'lv2-1.18.10.tar.xz'
            execute meson build --prefix="${workspace}" --buildtype='release' --default-library='static' --libdir="${workspace}"/lib
            execute ninja -C build
            execute ninja -C build install
            build_done 'lv2' '1.18.10'
        fi
        if build 'waflib' 'aeef9f5'; then
            download 'https://gitlab.com/drobilla/autowaf/-/archive/aeef9f5fdf416d9b68c61c75de7dae409f1ac6a4/autowaf-aeef9f5fdf416d9b68c61c75de7dae409f1ac6a4.tar.bz2' 'autowaf-aeef9f5.tar.bz2'
            build_done 'waflib' 'aeef9f5'
        fi
        if build 'serd' 'b4ac1ec'; then
            download 'https://gitlab.com/drobilla/serd/-/archive/b4ac1ec675b79cd05ed7ff2eda8f41002f3a51ef/serd-b4ac1ec675b79cd05ed7ff2eda8f41002f3a51ef.tar.bz2' 'serd-b4ac1ec.tar.bz2'
            execute meson build --prefix="${workspace}" --buildtype='release' --default-library='static' --libdir="${workspace}"/lib
            execute ninja -C build
            execute ninja -C build install
            build_done 'serd' 'b4ac1ec'
        fi
        if build 'pcre' '8.45'; then
            download 'https://cfhcable.dl.sourceforge.net/project/pcre/pcre/8.45/pcre-8.45.tar.bz2' 'pcre-8.45.tar.bz2'
            execute ./configure --prefix="${workspace}" --disable-shared --enable-static
            execute make "-j${cpus}"
            execute make install
            build_done 'pcre' '8.45'
        fi
        if build 'sord' '0.16.14'; then
            download 'https://gitlab.com/drobilla/sord/-/archive/v0.16.14/sord-v0.16.14.tar.gz' 'sord-v0.16.14.tar.gz'
            execute meson build --prefix="${workspace}" --buildtype='release' --default-library='static' --libdir="${workspace}"/lib
            execute ninja -C build
            execute ninja -C build install
            build_done 'sord' '0.16.14'
        fi
        if build 'sratom' '58418e5'; then
            download 'https://gitlab.com/lv2/sratom/-/archive/58418e5be2a491faa44d6d1c8d57052b1444814a/sratom-58418e5be2a491faa44d6d1c8d57052b1444814a.tar.bz2'  'sratom-58418e5.tar.bz2'
            # download 'https://gitlab.com/lv2/sratom/-/archive/v0.6.14/sratom-v0.6.14.tar.gz' 'sratom-v0.6.14.tar.gz'
            execute meson build --prefix="${workspace}" --buildtype='release' --default-library='static' --libdir="${workspace}"/lib
            execute ninja -C build
            execute ninja -C build install
            build_done 'sratom' '58418e5'
        fi
        if build 'lilv' '0.24.20'; then
            download 'https://gitlab.com/lv2/lilv/-/archive/v0.24.20/lilv-v0.24.20.tar.gz' 'lilv-v0.24.20.tar.gz'
            execute meson build --prefix="${workspace}" --buildtype='release' --default-library='static' --libdir="${workspace}"/lib
            execute ninja -C build
            execute ninja -C build install
            build_done 'lilv' '0.24.20'
        fi
        CFLAGS+=" -I${workspace}/include/lilv-0"
        cnf_ops+=('--enable-lv2')
    fi
fi

if build 'opencore' '0.1.6'; then
    download 'https://netactuate.dl.sourceforge.net/project/opencore-amr/opencore-amr/opencore-amr-0.1.6.tar.gz' 'opencore-amr-0.1.6.tar.gz'
    execute ./configure --prefix="${workspace}" --disable-shared --enable-static
    execute make "-j${cpus}"
    execute make install
    build_done 'opencore' '0.1.6'
fi
cnf_ops+=('--enable-libopencore_amrnb' '--enable-libopencore_amrwb')

if build 'lame' '3.100'; then
    download 'https://sourceforge.net/projects/lame/files/lame/3.100/lame-3.100.tar.gz/download?use_mirror=gigenet' 'lame-3.100.tar.gz'
    execute ./configure --prefix="${workspace}" --disable-shared --enable-static
    execute make "-j${cpus}"
    execute make install
    build_done 'lame' '3.100'
fi
cnf_ops+=('--enable-libmp3lame')

if build 'opus' '1.3.1'; then
    download 'https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz'
    execute ./configure --prefix="${workspace}" --disable-shared --enable-static
    execute make "-j${cpus}"
    execute make install
    build_done 'opus' '1.3.1'
fi
cnf_ops+=('--enable-libopus')

if build 'libogg' '1.3.5'; then
    download 'https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.5.tar.xz'
    execute ./configure --prefix="${workspace}" --disable-shared --enable-static
    execute make "-j${cpus}"
    execute make install
    build_done 'libogg' '1.3.5'
fi

if build 'libvorbis' '1.3.7'; then
    download 'https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.tar.xz'
    execute ./configure --prefix="${workspace}" --with-ogg-libraries="${workspace}"/lib \
        --with-ogg-includes="${workspace}"/include/ --enable-static --disable-shared --disable-oggtest
    execute make "-j${cpus}"
    execute make install
    build_done 'libvorbis' '1.3.7'
fi
cnf_ops+=('--enable-libvorbis')

if build 'libtheora' '1.1.1'; then
    download 'https://ftp.osuosl.org/pub/xiph/releases/theora/libtheora-1.1.1.tar.gz'
    sed "s/-fforce-addr//g" 'configure' >'configure.patched'
    chmod +x 'configure.patched'
    mv 'configure.patched' 'configure'
    rm 'config.guess'
    curl -Lso 'config.guess' 'https://raw.githubusercontent.com/gcc-mirror/gcc/master/config.guess'
    chmod +x 'config.guess'
    execute ./configure --prefix="${workspace}" --with-ogg-libraries="${workspace}"/lib --with-ogg-includes="${workspace}"/include/ \
        --with-vorbis-libraries="${workspace}"/lib --with-vorbis-includes="${workspace}"/include/ --enable-static --disable-shared \
        --disable-oggtest --disable-vorbistest --disable-examples --disable-asm --disable-spec
    execute make "-j${cpus}"
    execute make install
    build_done 'libtheora' '1.1.1'
fi
cnf_ops+=('--enable-libtheora')

if ${nonfree}; then
    if build 'fdk_aac' '2.0.2'; then
        download 'https://sourceforge.net/projects/opencore-amr/files/fdk-aac/fdk-aac-2.0.2.tar.gz/download?use_mirror=gigenet' 'fdk-aac-2.0.2.tar.gz'
        execute ./configure --prefix="${workspace}" --disable-shared --enable-static --enable-pic
        execute make "-j${cpus}"
        execute make install
        build_done 'fdk_aac' '2.0.2'
    fi
    cnf_ops+=('--enable-libfdk-aac')
fi

##
## image libraries
##

if build 'libtiff' '4.5.0'; then
    download 'https://download.osgeo.org/libtiff/tiff-4.5.0.tar.xz'
    execute ./configure --prefix="${workspace}" --disable-shared --enable-static --disable-dependency-tracking \
        --disable-lzma --disable-webp --disable-zstd --without-x
    execute make "-j${cpus}"
    execute make install
    build_done 'libtiff' '4.5.0'
fi
if build 'libpng' '1.6.39'; then
    download 'https://versaweb.dl.sourceforge.net/project/libpng/libpng16/1.6.39/libpng-1.6.39.tar.xz' 'libpng-1.6.39.tar.xz'
    export LDFLAGS="${LDFLAGS}"
    export CPPFLAGS="${CFLAGS}"
    execute ./configure --prefix="${workspace}" --disable-shared --enable-static
    execute make "-j${cpus}"
    execute make install
    build_done 'libpng' '1.6.39'
fi

if build 'libwebp' '1.2.2'; then
    # libwebp can fail to compile on Ubuntu if these flags were left set to CFLAGS
    CPPFLAGS=
    download 'https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.2.tar.gz' 'libwebp-1.2.2.tar.gz'
    execute ./configure --prefix="${workspace}" --disable-shared --enable-static --disable-dependency-tracking \
        --disable-gl --with-zlib-include="${workspace}"/include/ --with-zlib-lib="${workspace}"/lib
    make_dir build
    cd 'build'|| exit 1
    execute cmake -DCMAKE_INSTALL_PREFIX="${workspace}" -DCMAKE_INSTALL_LIBDIR='lib' -DCMAKE_INSTALL_BINDIR='bin' \
        -DCMAKE_INSTALL_INCLUDEDIR='include' -DENABLE_SHARED='OFF' -DENABLE_STATIC='ON' ../
    execute make "-j${cpus}"
    execute make install

    build_done 'libwebp' '1.2.2'
fi
  cnf_ops+=('--enable-libwebp')

##
## OTHER LIBRARIES
##

if build 'libsdl' '2.26.2'; then
    download 'https://www.libsdl.org/release/SDL2-2.26.2.tar.gz'
    execute ./configure --prefix="${workspace}" --disable-shared --enable-static
    execute make "-j${cpus}"
    execute make install
    build_done 'libsdl' '2.26.2'
fi

if ${nonfree}; then
    if build 'srt' '1.5.1'; then
        download 'https://github.com/Haivision/srt/archive/refs/tags/v1.5.1.tar.gz' 'srt-1.5.1.tar.gz'
        export OPENSSL_ROOT_DIR="${workspace}"
        export OPENSSL_LIB_DIR="${workspace}"/lib
        export OPENSSL_INCLUDE_DIR="${workspace}"/include/
        execute cmake . -DCMAKE_INSTALL_PREFIX="${workspace}" -DCMAKE_INSTALL_LIBDIR='lib' -DCMAKE_INSTALL_BINDIR='bin' \
            -DCMAKE_INSTALL_INCLUDEDIR='include' -DENABLE_SHARED='OFF' -DENABLE_STATIC='ON' -DENABLE_APPS='OFF' -DUSE_STATIC_LIBSTDCXX='ON'
        execute make install

        if [ -n "${LDEXEFLAGS}" ]; then
            sed -i.backup 's/-lgcc_s/-lgcc_eh/g' "${workspace}"/lib/pkgconfig/srt.pc
        fi
        build_done 'srt' '1.5.1'
    fi
        cnf_ops+=('--enable-libsrt')
fi


#####################
## HWaccel library ##
#####################

if which 'nvcc' &>/dev/null ; then
    if build 'nv-codec' '8.1.24.14'; then
        download 'https://github.com/FFmpeg/nv-codec-headers/releases/download/n8.1.24.14/nv-codec-headers-8.1.24.14.tar.gz'
        execute make PREFIX="${workspace}"
        execute make install PREFIX="${workspace}"
        build_done 'nv-codec' '8.1.24.14'
    fi
    CFLAGS+=' -I/usr/local/cuda-12.0/include'
    LDFLAGS+=' -L/usr/local/cuda-12.0/lib64'
    cnf_ops+=('--enable-cuda-nvcc' '--enable-cuvid' '--enable-nvenc' '--enable-cuda-llvm')

    if [ -z "${LDEXEFLAGS}" ]; then
        cnf_ops+=('--enable-libnpp')
    fi

    gpu_arch_fn
    # https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/ # cnf_ops+=('--nvccflags=-gencode arch=compute_52,code=sm_52')
    cnf_ops+=("--nvccflags=-gencode arch=${gpu_arch}")
fi

# Vaapi doesn't work well with static links FFmpeg.
if [ -z "${LDEXEFLAGS}" ]; then
    # If the libva development SDK is installed, enable vaapi.
    if library_exists 'libva'; then
        if build 'vaapi' '1'; then
            build_done 'vaapi' '1'
        fi
        cnf_ops+=('--enable-vaapi')
    fi
fi

if build 'amf' '1.4.29'; then
    download 'https://github.com/GPUOpen-LibrariesAndSDKs/AMF/archive/refs/tags/v1.4.29.tar.gz' 'AMF-1.4.29.tar.gz' 'AMF-1.4.29'
    execute rm -rf "${workspace}"/include/AMF
    execute mkdir -p "${workspace}"/include/AMF
    execute cp -fr "${packages}"/AMF-1.4.29/AMF-1.4.29/amf/public/include/* "${workspace}"/include/AMF/
    build_done 'amf' '1.4.29'
fi
cnf_ops+=('--enable-amf')

##
## BUILD FFMPEG
##

build 'ffmpeg' "${ffmpeg_ver::-33}"
download "https://git.ffmpeg.org/gitweb/ffmpeg.git/snapshot/${ffmpeg_ver}.tar.gz" "FFmpeg-snapshot-${ffmpeg_ver}.tar.gz"
# shellcheck disable=SC2086
./configure \
    "${cnf_ops[@]}" \
    --disable-debug \
    --disable-doc \
    --disable-shared \
    --enable-libfdk-aac \
    --enable-pthreads \
    --enable-static \
    --enable-small \
    --enable-version3 \
    --extra-cflags="${CFLAGS}" \
    --extra-ldexeflags="${LDEXEFLAGS}" \
    --extra-ldflags="${LDFLAGS}" \
    --extra-libs="${EXTRALIBS}" \
    --pkgconfigdir="${workspace}"/lib/pkgconfig \
    --pkg-config-flags='--static' \
    --prefix="${workspace}" \
    --extra-version="${EXTRA_VERSION}"

execute make "-j${cpus}"
execute make install

# MOVE BINARIES TO '/usr/bin'
sudo cp -f "${workspace}/bin/ffmpeg" "${install_dir}/ffmpeg"
sudo cp -f "${workspace}/bin/ffprobe" "${install_dir}/ffprobe"
sudo cp -f "${workspace}/bin/ffplay" "${install_dir}/ffplay"

# CHECK THAT FILES WERE COPIED TO THE ${install_dir}
if [ ! -f "${install_dir}/ffmpeg" ] || [ ! -f "${install_dir}/ffprobe" ] || [ ! -f "${install_dir}/ffplay" ]; then
    printf \
    "Failed to copy: %s to ${install_dir}\nFailed to copy: %s to ${install_dir}\nFailed to copy: %s to ${install_dir}\n" \
    "${install_dir}/ffmpeg" \
    "${install_dir}/ffprobe" \
    "${install_dir}/ffplay"
    echo
    exit 1
fi

ff_ver_fn
cleanup_fn
exit_fn
