#!/usr/bin/env bash
# Sudo command aliases

# System commands with sudo
alias pacman='sudo pacman'
alias aria2c='sudo aria2c'
alias cat='sudo cat'
alias chmod='sudo chmod'
alias chown='sudo chown'
alias crontab='sudo crontab'
alias ddclient='sudo ddclient'
alias dmesg='sudo dmesg'
alias docker-compose='sudo docker-compose'
alias docker='sudo docker'
alias dos2unix='sudo dos2unix'
alias egrep='sudo egrep'
alias fgrep='sudo fgrep'
alias find='sudo find'
alias grep='sudo grep'
alias killall='sudo killall'
alias kill='sudo kill'
alias ldconfig='sudo ldconfig'
alias ln='sudo ln'
alias mount='sudo mount'
alias nordvpn='sudo nordvpn'
alias passwd='sudo passwd'
alias service='sudo service'
alias systemctl='sudo systemctl'
alias timeshift='sudo timeshift'
alias ufw='sudo ufw'
alias umount='sudo umount'
alias unzip='sudo unzip'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias useradd='sudo useradd'
alias usermod='sudo usermod'
alias wget='sudo wget'
