#!/bin/bash
# shellcheck disable=SC2016,SC2034,SC2046,SC2066,SC2068,SC2086,SC2162,SC2317

######################################################
##
##  Install the latest curl release from GitHub
##
##  Supported OS:
##  - Debian 10 / 11
##  - Ubuntu 22.04 / 20.04 / 18.04
##
##  Updated: 06.14.23
##
##  Script version: 2.2
##
######################################################

clear

script_ver='2.2'
cwd="$PWD"/dltools-build-script
packages="$cwd"/packages
workspace="$cwd"/workspace
CFLAGS='-Os -ffunction-sections -fdata-sections -fno-unwind-tables -fno-asynchronous-unwind-tables -flto'
LDFLAGS="-L$workspace/lib64 -L$workspace/lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu"
LDFLAGS+=' -L/usr/local/lib -L/usr/lib64 -L/usr/lib -L/usr/local/lib -L/lib -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections'
CPPFLAGS="-I$workspace/include -I/usr/local/include -I/usr/include"
cert_dir='/etc/ssl/certs'
pem_file='cacert-2023-05-30.pem'
install_dir='/usr/local'
include_dir='/usr/include'
repo='https://github.com/slyfox1186/script-repo/'

#
# CREATE OUTPUT DIRECTORIES
#

mkdir -p "$packages" "$workspace"

#
# GET CPU CORE COUNT FOR PARALLEL PROCESSING
#

if [ -f '/proc/cpuinfo' ]; then
    cpu_threads="$(grep -c ^processor '/proc/cpuinfo')"
else
    cpu_threads="$(nproc --all)"
fi

#
# PRINT BANNER
#

printf "%s\n%s\n%s\n" \
    "DL-Tools Build Script - v$script_ver" \
    '===============================' \
    "This script will utilize ($cpu_threads) cpu threads for parallel processing to accelerate the build process."

#
# CREATE GLOBAL VARIABLES
#

PATH="\
/usr/lib/ccache:\
$workspace/bin:\
$HOME/.local/bin:\
$PATH\
"
export PATH

PKG_CONFIG_PATH="\
$workspace/lib64/pkgconfig:\
$workspace/lib/pkgconfig:\
/usr/local/lib/x86_64-linux-gnu/pkgconfig:\
/usr/local/lib64/pkgconfig:\
/usr/local/lib/pkgconfig:\
/usr/lib/x86_64-linux-gnu/lib/x86_64-linux-gnu/pkgconfig:\
/usr/lib/x86_64-linux-gnu/lib/pkgconfig:\
/usr/lib/x86_64-linux-gnu/pkgconfig:\
/usr/lib/i386-linux-gnu/pkgconfig:\
/usr/lib/pkgconfig:\
/usr/share/pkgconfig\
"
export PKG_CONFIG_PATH

#
# DEFINE FUNCTIONS
#

fail_fn()
{
    printf "\n%s\n\n%s\n%s\n\n" \
        "$1" \
        'Please submit a support ticket in GitHub.' \
    "$repo"
    exit 1
}

exit_fn()
{
    printf "\n%s\n\n%s\n\n" \
        'Make sure to star this repository to show your support!' \
        "$repo"
    exit 0
}

cleanup_fn()
{
    printf "\n%s\n\n%s\n%s\n\n" \
        'Do you want to cleanup the build files?' \
        '[1] Yes' \
        '[2] No'
    read -p 'Your choices are (1 or 2): ' my_choice
    case "$my_choice" in
    1)
        sudo rm -fr "$cwd"
        exit_fn
        ;;
    2)
        exit_fn
        ;;
    *)
        read -p 'Bad user input. Press enter to try again'
        echo
        cleanup_fn
        ;;
    esac
}

success_fn()
{
    local curl_ver wget_ver
    curl_ver="$(curl --version | grep -Eo '[0-9\.]+' | sed -n 1p)"
    wget_ver="$(wget --version | grep -Eo '[0-9\.]+' | sed -n 1p)"
    printf "\n%s\n\n" "The updated cURL version is: v$curl_ver"
    printf "\n%s\n\n" "The updated WGET version is: v$wget_ver"
    sleep 4
}

#
# SCRAPE GITHUB WEBSITE FOR THE LATEST REPO VERSION
#

curl_timeout='10'

git_1_fn()
{
    local curl_cmd github_repo github_url

    github_repo="$1"
    github_url="$2"

    if curl_cmd="$(curl -m "$curl_timeout" -sSL "https://api.github.com/repos/$github_repo/$github_url")"; then
        g_ver="$(echo "$curl_cmd" | jq -r '.[0].name' 2>/dev/null)"
        g_url="$(echo "$curl_cmd" | jq -r '.[0].tarball_url' 2>/dev/null)"
        g_ver="${g_ver#cares-}"
        g_ver="${g_ver#nghttp2 v}"
        g_ver="${g_ver#nghttp3 v}"
        g_ver="${g_ver#OpenSSL }"
        g_ver="${g_ver#release-}"
        g_ver="${g_ver#v}"
    fi

}

git_ver_fn()
{
    local v_flag v_url v_tag url_tag gv_url

    v_url="$1"
    v_tag="$2"

    if [ -n "$3" ]; then
        v_flag="$3"
    fi

    case "$v_flag" in
        T)      gv_url='tags' ;;
        R)      gv_url='releases' ;;
        *)      fail_fn 'tags and releases were not among the URL options.' ;;
    esac

    case "$v_tag" in
        1)      url_tag='git_1_fn';;
        *)      fail_fn 'Could not detect the $v_tag variable inside the git_ver_fn() function';;
    esac

    "$url_tag" "$v_url" "$gv_url" 2>/dev/null
}

execute()
{
    echo "$ $*"
    if ! output=$("$@" 2>&1); then
        fail_fn "Failed to Execute $*"
    fi
}

download()
{
    dl_path="$packages"
    dl_url="$1"
    dl_file="${2:-"${1##*/}"}"

    if [[ "$dl_file" =~ tar. ]]; then
        output_dir="${dl_file%.*}"
        output_dir="${3:-"${output_dir%.*}"}"
    else
        output_dir="${3:-"${dl_file%.*}"}"
    fi

    target_file="$dl_path/$dl_file"
    target_dir="$dl_path/$output_dir"

    if [ -f "$target_file" ]; then
        echo "The file \"$dl_file\" is already downloaded."
    else
        echo "Downloading \"$dl_url\" saving as \"$dl_file\""
        if ! curl -Lso "$target_file" "$dl_url"; then
            printf "\n%s\n\n" "The script failed to download \"$dl_file\" and will try again in 5 seconds..."
            sleep 5
            if ! curl -Lso "$target_file" "$dl_url"; then
                fail_fn "The script failed to download \"$dl_file\" twice and will now exit."
            fi
        fi
        echo 'Download Completed'
    fi

    if [ -d "$target_dir" ]; then
        sudo rm -fr "$target_dir"
    fi

    mkdir -p "$target_dir"

    if [ -n "$3" ]; then
        if ! tar -xf "$target_file" -C "$target_dir" 2>/dev/null >/dev/null; then
            sudo rm "$target_file"
            fail_fn "Failed to extract \"$dl_file\" so it was deleted. Please run the script again."
        fi
    else
        if ! tar -xf "$target_file" -C "$target_dir" --strip-components 1 2>/dev/null >/dev/null; then
            sudo rm "$target_file"
            fail_fn "Failed to extract \"$dl_file\" so it was deleted. Please run the script again."
        fi
    fi

    echo -e "File extracted: $dl_file\\n"

    cd "$target_dir" || fail_fn "Unable to change the working directory to: $target_dir"
}

download_alt()
{
    local dl_path dl_file target_dir

    dl_path="$packages"
    dl_file="$1"
    target_dir="$dl_path/$dl_file"

    curl -Lso "$target_dir.tar.gz" 'https://ftp.gnu.org/gnu/wget/wget-latest.tar.gz'
    mkdir -p "$target_dir"
    tar -xf "$target_dir.tar.gz" -C "$target_dir" --strip-components 1
    cd "$target_dir" || exit 1
    g_ver="$(cat '.version')"
    sudo rm -fr "$target_dir" "$target_dir.tar.gz"
}

build()
{
    printf "\n%s\n%s\n" \
        "building $1 - version $2" \
        '===================================='

    if [ -f "$packages/$1.done" ]; then
        if grep -Fx "$2" "$packages/$1.done" > /dev/null; then
            echo "$1 version $2 already built. Remove $packages/$1.done lockfile to rebuild it."
            return 1
        else
            echo "$1 is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove $packages/$1.done lockfile."
            return 1
        fi
    fi

    return 0
}

build_done() { echo "$2" > "$packages/$1.done"; }

installed() { return $(dpkg-query -W -f '${Status}\n' "$1" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }

#
# INSTALL REQUIRED APT PACKAGES
#

pkgs_fn()
{
    local pkg pkgs missing_pkgs

    pkgs=("$1" autoconf autogen automake autopoint autotools-dev build-essential ccache cmake curl git google-perftools jq lcov
          libaria2-0 libaria2-0-dev libcppunit-dev libcunit1-dev libcurl4-gnutls-dev libec-dev libev-dev libevent-dev libexiv2-27 \
          libgcc-12-dev libgexiv2-2 libgimp2.0 libldap-dev libldap2-dev liblzma-dev libmbedtls-dev libnghttp2-dev libntlm0-dev \
          libpsl-dev librtmp-dev libssh-dev libssh2-1-dev libtool libzstd-dev m4 pkg-config python3-pip re2c libunistring-dev \
          libuv1-dev)

    for pkg in ${pkgs[@]}
    do
        if ! installed "$pkg"; then
            missing_pkgs+=" $pkg"
        fi
    done

    if [ -n "${missing_pkgs-}" ]; then
        printf "\n%s\n%s\n" \
            'Installing required apt packages' \
            '================================================'
        for i in "$missing_pkgs"; do
            echo "\$ sudo apt -y install $i"
            sudo apt -y install $i
            echo
        done
    fi
}

#
# DISCOVER THE SYSTEM OS
#

pkgs_jammy='libnghttp3-dev libgsasl-dev libngtcp2-dev'

os_test="$(lsb_release -r 2>/dev/null | grep -Eo '[0-9\.]+$')"
if [ "$os_test" = '23.04' ] || [ "$os_test" = '22.04' ]; then
    pkgs_fn "$pkgs_jammy"
    j_flag='nghttp3=/usr/include'
fi

#
# SET THE C & C++ COMPILERS
#

if ! type -P gcc &>/dev/null && export CC=gcc CXX=g++; then
    fail_fn 'No C compilers were located. Please install "gcc and g++".'
fi

#
# SET THE C++ COMPILER OPTIMIZATION FLAGS TO TUNE THE BUILD FOR THE SPECIFIC COMPUTER RUNNING THE SCRIPT 
#

export CXXFLAGS='-g -O3 -march=native -mtune=native'

#
# INSTALL CA CERTS FROM CURL'S OFFICIAL WEBSITE
#

if [ ! -f "$cert_dir/$pem_file" ]; then
    execute wget -cqO "$pem_file" "https://curl.se/ca/$pem_file"
    execute sudo mv "$pem_file" "$cert_dir/$pem_file"
fi

#
# COMPILE FROM SOUCE CODE
#

git_ver_fn 'madler/zlib' '1' 'T'
if build 'zlib' "$g_ver"; then
    download "$g_url" "zlib-$g_ver.tar.gz"
    execute ./configure --prefix="$workspace" --static
    execute make "-j$(($cpu_threads-1))"
    execute make install
    build_done 'zlib' "$g_ver"
fi

git_ver_fn 'akheron/jansson' '1' 'T'
if build 'jansson' "$g_ver"; then
    download "$g_url" "jansson-$g_ver.tar.gz"
    execute autoreconf -fi
    execute ./configure --prefix="$workspace"
    execute make "-j$(($cpu_threads-1))"
    execute make install
    build_done 'jansson' "$g_ver"
fi

if build 'gsasl' '2.2.0'; then
    download 'https://ftp.gnu.org/gnu/gsasl/gsasl-2.2.0.tar.gz' 'gsasl-2.2.0.tar.gz'
    execute ./configure --prefix="$workspace"
    execute make "-j$(($cpu_threads-1))"
    execute make install
    sudo cp -f "$workspace"/lib/libgsasl.so.18 /usr/local/lib
    build_done 'gsasl' '2.2.0'
fi

git_ver_fn 'c-ares/c-ares' '1' 'R'
g_ver="${g_ver//cares-/}"
g_tag="${g_ver//\./_}"
if build 'c-ares' "$g_ver"; then
    download "https://codeload.github.com/c-ares/c-ares/tar.gz/refs/tags/cares-$g_tag" "c-ares-$g_ver.tar.gz"
    execute autoupdate
    execute autoreconf -fi
    execute ./configure --prefix="$workspace" --disable-{shared,warnings} --enable-optimize="$CXXFLAGS"
    execute make "-j$(($cpu_threads-1))"
    execute make install
    execute make distclean
    build_done 'c-ares' "$g_ver"
fi

git_ver_fn 'pcre2project/pcre2' '1' 'T'
if build 'pcre2' "$g_ver"; then
    download "$g_url" "pcre2-$g_ver.tar.gz"
    execute ./autogen.sh
    execute ./configure --prefix="$workspace" --enable-static \
        --disable-shared CFLAGS="$CFLAGS" CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS"
    execute make "-j$(($cpu_threads-1))"
    execute make install
    build_done 'pcre2' "$g_ver"
fi

git_ver_fn 'jemalloc/jemalloc' '1' 'T'
if build 'jemalloc' "$g_ver"; then
    download "https://codeload.github.com/jemalloc/jemalloc/tar.gz/refs/tags/$g_ver" "jemalloc-$g_ver.tar.gz"
    execute ./autogen.sh
    execute ./configure --prefix="$workspace" --enable-{autogen,lazy-lock,static,xmalloc} \
        --disable-{debug,doc,fill,log,shared,prof,stats}
    execute make "-j$(($cpu_threads-1))"
    execute make install
    build_done 'jemalloc' "$g_ver"
fi

git_ver_fn 'google/brotli' '1' 'T'
if build 'brotli' "$g_ver"; then
    download "$g_url" "brotli-$g_ver.tar.gz"
    mkdir build
    cd build || exit 1
    execute ../configure-cmake --prefix="$workspace"
    execute make "-j$(($cpu_threads-1))"
    execute make test
    execute make install
    build_done 'brotli' "$g_ver"
fi

#
# START CURL & WGET BUILD
#

download_alt 'wget'
if build 'wget' "$g_ver"; then
    download "https://ftp.gnu.org/gnu/wget/wget-$g_ver.tar.gz" "wget-$g_ver.tar.gz"
    if which 'update-ca-certificates' &>/dev/null; then
        execute sudo update-ca-certificates
    fi
    execute autoconf
    ./configure --prefix="$install_dir" --enable-threads --with-ssl=gnutls --with-metalink \
        --with-cares --with-openssl=auto CFLAGS="$CFLAGS" CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS" \
        PCRE_LIBS="$workspace"/lib
    execute make "-j$(($cpu_threads-1))"
    execute sudo make install
    build_done 'wget' "$g_ver"
fi

git_ver_fn 'curl/curl' '1' 'R'
if build 'curl' "$g_ver"; then
    download "$g_url" "curl-$g_ver.tar.gz"
    curl_disable_opts=(--disable-{get-easy-options,shared,verbose,versioned-symbols})
    curl_enable_opts=(--enable-{alt-svc,ares="$workspace/include",cookies,crypto-auth,dateparse,dict,dnsshuffle,doh,file,ftp,gopher})
    curl_enable_opts+=(--enable-{headers-api,hsts,http,http-auth,imap,ipv6,ldap,ldaps,libcurl-option,libgcc,manual,mime,mqtt,netrc,ntlm,ntlm-wb='/usr/bin/ntlm_auth'})
    curl_enable_opts+=(--enable-{openssl-auto-load-config,optimize,pop3,progress-meter,proxy,pthreads,rtsp,smb,smtp,socketpair,sspi,static,telnet,tftp,threaded-resolver})
    curl_enable_opts+=(--enable-{tls-srp,unix-sockets,websockets})
    curl_with_opts=(--with-{gnutls="$include_dir",libssh2,gssapi="$include_dir"/globus,nghttp2='/usr/include'})
    curl_with_opts+=(--with-{ca-bundle="$cert_dir/$pem_file",ca-fallback,ca-path="$cert_dir",secure-transport})
    execute autoreconf -fi
    ./configure --prefix="$install_dir" "${curl_disable_opts[@]}" "${curl_enable_opts[@]}" \
        "${curl_with_opts[@]}" CFLAGS="$CFLAGS" CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS" --with-"$j_flag" 
    execute make "-j$(($cpu_threads-1))"
    execute sudo make install
fi

sudo ldconfig &>/dev/null

# OUTPUT FINAL MESSAGES TO USER IN TERMINAL
success_fn

# CLEANUP LEFTOVER FILES
cleanup_fn
