#!/usr/bin/env bash

clear

# GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-gettext-libiconv
# Purpose: build gnu gettext + libiconv
# Updated: 08.31.23
# Script version: 1.2

set -e

if [ "${EUID}" -eq '0' ]; then
    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
    exit 1
fi

script_ver=1.2
archive_dir1=libiconv-1.17
archive_dir2=gettext-0.22.4
archive_url1=https://ftp.gnu.org/gnu/libiconv/$archive_dir1.tar.gz
archive_url2=https://ftp.gnu.org/gnu/gettext/$archive_dir2.tar.lz
cwd="${PWD}"/gettext-libiconv-build-script
install_dir=/usr/local

# Helper function to download and extract archives
download_and_extract()
{
    local archive_dir=$1
    local archive_url=$2
    local archive_ext="${archive_url##*.}"

    mkdir -p "$cwd/$archive_dir"
    curl -L "${archive_url}" -o "$cwd/$archive_dir.${archive_ext}"
    tar -xf "$cwd/$archive_dir.${archive_ext}" -C "$cwd/$archive_dir" --strip-components 1
}

# Helper function for building and installing
build_and_install()
{
    local archive_dir=$1
    cd "$cwd/$archive_dir" || exit 1
    mkdir -p build
    cd build || exit 1
    ../configure --prefix="$install_dir" --enable-static --with-pic
    if ! make "-j$(nproc --all)"; then
        printf "%s\n\n" "Failed to run make -j$(nproc --all)"
        exit 1
    fi
    if ! sudo make install; then
        printf "%s\n\n" 'Failed to run sudo make install'
        exit 1
    fi
    sudo libtool --finish "$install_dir/lib"
}

# Main script execution
printf "%s\n%s\n\n"                                  \
    "gettext + libiconv build script - v$script_ver" \
    '==============================================='

download_and_extract "$archive_dir1" "${archive_url1}"
build_and_install "$archive_dir1"

download_and_extract "$archive_dir2" "${archive_url2}"
build_and_install "$archive_dir2"
