#!/usr/bin/env bash

###########################################################################################################
##
##  GitHub Script: https://github.com/slyfox1186/script-repo/edit/main/Bash/Installer%20Scripts/GNU%20Software/build-nano
##
##  Purpose: Build GNU nano
##
##  Updated: 08.03.23
##
##  Script version: 1.0
##
###########################################################################################################

clear

if [ "$EUID" -eq '0' ]; then
    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
    exit 1
fi

#
# SET VARIABLES
#

script_ver=1.0
archive_dir=nano-7.2
archive_url=https://ftp.gnu.org/gnu/nano/nano-7.2.tar.xz
archive_ext="${archive_url//*.}"
cwd="$PWD"/nano-build-script
user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
repo=https://github.com/slyfox1186/script-repo

printf "\n%s\n%s\n\n" \
    "nano build script - v$script_ver" \
    '==============================================='

#
# CREATE OUTPUT DIRECTORY
#

if [ ! -d "$cwd" ]; then
    mkdir -p "$cwd"
fi

#
# SET THE C+CPP COMPILERS
#

export CC=gcc CXX=g++

#
# SET THE PATH VARIABLE
#

PATH="\
/usr/lib/ccache:\
$HOME/.cargo/bin:\
$HOME/.local/bin:\
/usr/local/sbin:\
/usr/local/bin:\
/usr/sbin:\
/usr/bin:\
/sbin:\
/bin:\
/usr/local/cuda/bin:\
/snap/bin\
"
export PATH

#
# SET THE PKG_CONFIG_PATH VARIABLE
#

PKG_CONFIG_PATH="\
/usr/local/lib64/pkgconfig:\
/usr/local/lib/pkgconfig:\
/usr/local/lib/x86_64-linux-gnu/pkgconfig:\
/usr/local/share/pkgconfig:\
/usr/lib64/pkgconfig:\
/usr/lib/pkgconfig:\
/usr/lib/x86_64-linux-gnu/pkgconfig:\
/usr/share/pkgconfig:\
/lib64/pkgconfig:\
/lib/pkgconfig:\
/lib/x86_64-linux-gnu/pkgconfig\
"
export PKG_CONFIG_PATH

#
# SET COMPILER OPTIMIZATION FLAGS
#

export {CFLAGS,CXXFLAGS}='-g -O2 -flto -ffunction-sections -fdata-sections -pipe -march=native'

#
# CREATE FUNCTIONS
#

exit_fn()
{
    printf "\n%s\n\n%s\n\n" \
        'Make sure to star this repository to show your support!' \
        "$repo"
    exit 0
}

fail_fn()
{
    printf "\n%s\n\n%s\n\n" \
        "$1" \
        "To report a bug create an issue at: $repo/issues"
    exit 1
}

cleanup_fn()
{
    local choice

    printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
        '============================================' \
        '  Do you want to clean up the build files?  ' \
        '============================================' \
        '[1] Yes' \
        '[2] No'
    read -p 'Your choices are (1 or 2): ' choice

    case "$choice" in
        1)      sudo rm -fr "$cwd";;
        2)      echo;;
        *)
                clear
                printf "%s\n\n" 'Bad user input. Reverting script...'
                sleep 3
                unset choice
                clear
                cleanup_fn
                ;;
    esac
}

#
# INSTALL REQUIRED APT PACKAGES
#

pkgs_fn()
{
    pkgs=("$1" autoconf autoconf-archive autogen automake binutils bison build-essential bzip2 ccache curl
          libc6-dev libintl-perl libpth-dev libtool libtool-bin lzip lzma-dev m4 nasm texinfo
          zlib1g-dev yasm)

    for i in ${pkgs[@]}
    do
        missing_pkg="$(sudo dpkg -l | grep -o "$i")"
    
        if [ -z "$missing_pkg" ]; then
            missing_pkgs+=" $i"
        fi
    done
    
    if [ -n "$missing_pkgs" ]; then
        sudo apt -y install $missing_pkgs
        sudo apt -y autoremove
        clear
    fi
}

#
# GET PC TYPE
#

curl -A "$user_agent" -Lso "$cwd/config.guess" 'https://raw.githubusercontent.com/gcc-mirror/gcc/master/config.guess'
chmod +x "$cwd/config.guess"
pc_type="$(source "$cwd/config.guess")"

#
# DOWNLOAD THE ARCHIVE FILE
#

archive_name="$archive_dir.tar.$archive_ext"

if [ ! -f "$cwd/$archive_name" ]; then
    curl -A "$user_agent" -Lso "$cwd/$archive_name" "$archive_url"
fi

#
# CREATE OUTPUT DIRECTORY
#

if [ -d "$cwd/$archive_dir" ]; then
    sudo rm -fr "$cwd/$archive_dir"
fi
mkdir -p "$cwd/$archive_dir/build"

#
# EXTRACT ARCHIVE FILES
#

if ! tar -zxf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
    exit 1
fi

#
# BUILD PROGRAM FROM SOURCE
#

cd "$cwd/$archive_dir" || exit 1
autoreconf -fi
cd build || exit 1
../configure --help
exit
../configure --prefix=/usr/local               \
             --{build,host}="$pc_type"         \
             --disable-nls                     \
             --enable-alias                    \
             --enable-arith-for-command        \
             --enable-array-variables          \
             --enable-brace-expansion          \
             --enable-casemod-attributes       \
             --enable-casemod-expansions       \
             --enable-command-timing           \
             --enable-cond-command             \
             --enable-cond-regexp              \
             --enable-coprocesses              \
             --enable-debugger                 \
             --enable-dev-fd-stat-broken       \
             --enable-directory-stack          \
             --enable-direxpand-default        \
             --enable-disabled-builtins        \
             --enable-dparen-arithmetic        \
             --enable-extended-glob            \
             --enable-extended-glob-default    \
             --enable-function-import          \
             --enable-glob-asciiranges-default \
             --enable-help-builtin             \
             --enable-history                  \
             --enable-job-control              \
             --enable-mem-scramble             \
             --enable-multibyte                \
             --enable-net-redirections         \
             --enable-process-substitution     \
             --enable-profiling                \
             --enable-progcomp                 \
             --enable-prompt-string-decoding   \
             --enable-readline                 \
             --enable-restricted               \
             --enable-select                   \
             --enable-separate-helpfiles       \
             --enable-single-help-strings      \
             --enable-strict-posix-default     \
             --enable-threads=posix            \
             --enable-translatable-strings     \
             --enable-usg-echo-default         \
             --enable-xpg-echo-default         \
             --with-nano-malloc                \
             --with-curses                     \
             --with-gnu-malloc                 \
             --with-included-gettext           \
             --with-installed-readline         \
             --with-libiconv-prefix=/usr       \
             --with-libintl-prefix=/usr        \
             --with-libpth-prefix=/usr
make "-j$(nproc --all)"
if ! sudo make install; then
    make distclean
    printf "\n%s\n\n" 'Failed to install nano.'
    exit 1
fi

# PROMPT USER TO CLEAN UP FILES
cleanup_fn

# SHOW EXIT MESSAGE
exit_fn
