#!/bin/bash

clear

printf "%s\n\n%s\n%s\n%s\n\n" \
    'Choose an option' \
    '[1] Install' \
    '[2] Uninstall' \
    '[3] Change shell to BASH (fixes zsh issues after it is uninstalled)'
    read -p 'Your choices are (1 to 3): ' tilix_choice

case "$tilix_choice" in
    1) 
        bash 'install-tilix';;
    2)
        sudo bash 'remove-tilix';;
    3)
        sudo chsh --shell=/bin/bash "$USER";;
    *)
        echo 'Bad user input. Run the script again.';;
esac
