#!/bin/bash

clear

if ! which 'git'; then
    sudo apt -y install git &>/dev/null
fi

if ! which 'libtool'; then
    sudo apt -y install libtool &>/dev/null
fi

if [ -d 'script-repo' ]; then
    sudo rm -fr 'script-repo'
fi

git clone -n --depth=1 --filter=tree:0 \
  https://github.com/slyfox1186/script-repo script-repo
cd script-repo || exit 1
git sparse-checkout set --no-cone shell/installers/tilix
git checkout

echo -e "\\nThe files have been downloaded to the terminals working directory. Open your file manager and find the file install-tilix.\\n"
echo -e "The script will have brief instuctions of how to customize the color themes you want to add or remove.\\n"
echo -e "After your changes are made open the terminal to the same folder as 'install-tilix' and execute the command: bash install-tilix\\n"
