#!/bin/bash
# Sudo command aliases

# System commands with sudo
alias alien='sudo alien'
alias apt-get='sudo apt-get'
alias apt='sudo apt'
alias aptitude='sudo aptitude'
alias apt-key='sudo apt-key'
alias aria2c='sudo aria2c'
alias cat='sudo cat'
alias chmod='sudo chmod'
alias chown='sudo chown'
alias crontab='sudo crontab'
alias ddclient='sudo ddclient'
alias dmesg='sudo dmesg'
alias docker-compose='sudo docker-compose'
alias docker='sudo docker'
alias dos2unix='sudo dos2unix'
alias dpkg='sudo dpkg'
alias egrep='sudo egrep'
alias fgrep='sudo fgrep'
alias find='sudo find'
alias grep='sudo grep'
alias killall='sudo killall'
alias kill='sudo kill'
alias ldconfig='sudo ldconfig'
alias ln='sudo ln'
alias mainline='sudo mainline'
alias mount='sudo mount'
alias netplan='sudo netplan'
alias nordvpn='sudo nordvpn'
alias passwd='sudo passwd'
alias rpm='sudo rpm'
alias service='sudo service'
alias snap='sudo snap'
alias systemctl='sudo systemctl'
alias timeshift='sudo timeshift'
alias ufw='sudo ufw'
alias umount='sudo umount'
alias unzip='sudo unzip'
alias update-grub='sudo update-grub'
alias useradd='sudo useradd'
alias usermod='sudo usermod'
alias wget='sudo wget'

# Fix known issues
alias fix_gpg='sudo cp /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d'