#!/usr/bin/env bash


clear

if [ "$EUID" -eq '0' ]; then
    echo "You must run this script without root or sudo."
    exit 1
fi


script_ver=1.1
archive_dir=aria2-1.37.0
archive_url=https://github.com/aria2/aria2/releases/download/release-1.37.0/aria2-1.37.0.tar.gz
archive_ext="$archive_url//*."
cwd="$PWD"/aria2-build-script
user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
web_repo=https://github.com/slyfox1186/script-repo

printf "\n%s\n%s\n\n" \
    "Aria2 Build Script (Raspberry Pi Edition) v$script_ver" \
    '======================================================'
sleep 2


if [ ! -d "$cwd" ]; then
    mkdir -p "$cwd"
fi


export CC=gcc CXX=g++


export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -fno-plt -march=native'


exit_fn() {
    printf "\n%s\n\n%s\n\n" \
        'Make sure to star this repository to show your support!' \
        "$web_repo"
    exit 0
}

fail_fn() {
    printf "\n%s\n\n%s\n\n" \
        "$1" \
        "To report a bug create an issue here: $web_repo/issues"
    exit 1
}

cleanup_fn() {
    local choice
    
    unset archive_dir archive_ext archive_name archive_url CC CXX i missing_pkg missing_pkgs pc_type pem_target pkgs script_ver

    if sudo dpkg -l | grep aria2 &>/dev/null; then
        sudo apt remove aria2
        sudo apt -y autoremove
        clear
    fi

    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
        '============================================' \
        '  Do you want to clean up the build files?  ' \
        '============================================' \
        '[1] Yes' \
        '[2] No'
    read -p 'Your choices are (1 or 2): ' choice

    case "$choice" in
        1)      sudo rm -fr "$cwd";;
        2)      echo;;
        *)
                clear
                printf "%s\n\n" 'Bad user input. Reverting script...'
                sleep 3
                unset choice
                clear
                cleanup_fn
                ;;
    esac
}


pkgs=(autoconf autogen automake build-essential ca-certificates ccache clang curl libaria2-0 libaria2-0-dev
      libc-ares-dev libdmalloc-dev libgcrypt20-dev libgmp-dev libgnutls28-dev libgpg-error-dev libjemalloc-dev
      libmbedtls-dev libnghttp2-dev librust-openssl-dev libsqlite3-dev libssh2-1-dev libssh-dev libssl-dev
      libuv1-dev libxml2-dev pkg-config zlib1g-dev)

for i in ${pkgs[@]}
do
    missing_pkg="$(dpkg -l | grep "$i")"

    if [ -z "$missing_pkg" ]; then
        missing_pkgs+=" $i"
    fi
done

if [ -n "$missing_pkgs" ]; then
    sudo apt install $missing_pkgs
    sudo apt -y autoremove
    clear
fi


curl -A "$user_agent" -Lso "$cwd/config.guess" 'https://raw.githubusercontent.com/gcc-mirror/gcc/master/config.guess'
chmod +x "$cwd/config.guess"
pc_type="$(source "$cwd/config.guess")"


archive_name="$archive_dir.tar.$archive_ext"

if [ ! -f "$cwd/$archive_name" ]; then
    curl -A "$user_agent" -Lso "$cwd/$archive_name" "$archive_url"
fi


if [ -d "$cwd/$archive_dir" ]; then
    sudo rm -fr "$cwd/$archive_dir"
fi
mkdir -p "$cwd/$archive_dir/build"


if ! tar -zxf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
    exit 1
fi


cd "$cwd/$archive_dir" || exit 1
sed -i 's/1, 16/1, 128/g' 'src/OptionHandlerFactory.cc'
cd build || exit 1
../configure --prefix=/usr/local              \
             --{build,host,target}="$pc_type" \
             --disable-nls                    \
             --disable-shared                 \
             --disable-werror                 \
             --enable-libaria2                \
             --enable-static                  \
             --with-ca-bundle="$pem_target"   \
             --with-libgcrypt                 \
             --with-libuv                     \
             --with-jemalloc                  \
             --with-openssl                   \
             --without-gnutls                 \
             --without-libnettle              \
             ARIA2_STATIC=yes                 \
             LIBS="$(pkg-config --libs libuv)"
make "-j$(nproc --all)"
if ! sudo make install; then
    make distclean
    printf "\n%s\n\n" 'Failed to install aria2.'
    exit 1
fi


if [ -f /usr/local/bin/"$pc_type"-aria2c ]; then
    sudo ln -sf /usr/local/bin/"$pc_type"-aria2c /usr/local/bin/aria2c
    sudo chmod 755 /usr/local/bin/aria2c
fi

cleanup_fn

exit_fn
