#!/Usr/bin/env bash


clear

printf "Installing DMD -- version latest\n======================================\n"

echo 'Fetching the latest DMD version.'
version=$(curl -s https://downloads.dlang.org/releases/LATEST)

if [ -z "$version" ]; then
    printf "Failed to capture DLang version.\n\n"
    exit 1
fi

user_agents=("Mozilla/5.0" "Opera/9.80" "Chrome/41.0.2228.0" "Safari/537.36")

echo "Downloading the install script for DMD version $version."
temp_script=$(mktemp)
download_success=0

for agent in "${user_agents[@]}"; do
    if wget -U "$agent" -nv --tries=3 --timeout=10 -O "$temp_script" https://dlang.org/install.sh; then
        download_success=1
        break
    else
        echo "Download failed with user agent: $agent"
    fi
done

if [ $download_success -eq 0 ]; then
    printf "Failed to download the install script after retries.\n\n"
    rm -f "$temp_script"
    exit 1
fi

echo 'Setting script permissions.'
chmod +x "$temp_script"

echo "Installing DMD version $version"
if ! "$temp_script" > /dev/null 2>&1; then
    printf "\nInstallation of DMD failed.\n\n"
    rm -f "$temp_script"
    exit 1
fi

printf "Make sure to star this repository to show your support!\nhttps://github.com/slyfox1186/script-repo\n"

cat >> "$HOME/.bashrc" <<EOF

export PATH="\$PATH:\$HOME/dlang/dmd-$version/linux/bin64"
EOF

source "$HOME"/.bashrc

rm -f "$temp_script"
exit 0
