#!/bin/bash
clear

#
# MENU COLOR FUNCTIONS
#

green='\e[32m'
blue='\e[34m'
clear='\e[0m'
ColorGreen() { echo -ne "$green$1$clear"; }
ColorBlue() { echo -ne "$blue$1$clear"; }

#
# SHOW SCRIPT BANNER
#

function box_out_banner()
{
    input_char=$(echo "$@" | wc -c)
    line=$(for i in `seq 0 $input_char`; do printf "-"; done)
    tput bold
    line="$(tput setaf 3)${line}"
    space=${line//-/ }
    echo " ${line}"
    printf '|' ; echo -n "$space" ; printf "%s\n" '|';
    printf '| ' ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" ' |';
    printf '|' ; echo -n "$space" ; printf "%s\n" '|';
    echo " ${line}"
    tput sgr 0
}

#
# DOWNLOAD SCRIPTS
#

szip_release_fn() { bash <(curl -sSL https://7z.optimizethis.net); }
dl_tools_fn() { bash <(curl -sSL https://dl-tools.optimizethis.net); }
build_tools_fn() { bash <(curl -sSL https://build-tools.optimizethis.net); }
magick_fn() { bash <(curl -sSL https://magick.optimizethis.net) --build --latest; }
ffmpeg_fn() { bash <(curl -sSL https://build-ffmpeg.optimizethis.net) --build --enable-gpl-and-non-free --latest; }
go_fn() { bash <(curl -sSL https://go.optimizethis.net); }
gparted_fn() { bash <(curl -sSL https://gparted.optimizethis.net); }
deb_dl_fn() { bash <(curl -sSL https://download.optimizethis.net); }
video_fn() { bash <(curl -sSL https://players.optimizethis.net); }

box_out_banner 'Installer Script Menu'

#
# DISPLAY CUSTOM USER SCRIPTS MENU
#

custom_user_scripts()
{
    local answer
echo -ne "
$(ColorGreen '1)')  Ubuntu Lunar
$(ColorGreen '2)')  Ubuntu Jammy, Focal, or Bionic
$(ColorGreen '0)')  Exit
$(ColorBlue 'Choose an option:') "
    read answer
    case "$answer" in
        1)
            clear
            bash <(curl -sSL https://lunar-scripts.optimizethis.net)
            clear
            main_menu
            ;;
        2)
            clear
            bash <(curl -sSL https://jammy-scripts.optimizethis.net)
            clear
            main_menu
            ;;
        0)
            clear
            main_menu
            ;;
        *)
            echo $red'Wrong option'$clear
            WrongCommand
            ;;
    esac
}

#
# DISPLAY EXTRA MIRRORS MENU
#

extra_mirrors()
{
    local answer
echo -ne "
$(ColorGreen '1)')  Ubuntu Lunar
$(ColorGreen '2)')  Ubuntu Jammy
$(ColorGreen '3)')  Ubuntu Focal
$(ColorGreen '4)')  Ubuntu Bionic
$(ColorGreen '5)')  Debian Bullseye
$(ColorGreen '0)')  Exit
$(ColorBlue 'Choose an option:') "
    read answer
    case "$answer" in
        1)
            clear
            curl -Lso mirrors https://lunar-mirrors.optimizethis.net; sudo bash mirrors
            clear
            main_menu
            ;;
        2)
            clear
            curl -Lso mirrors https://jammy-mirrors.optimizethis.net; sudo bash mirrors
            clear
            main_menu
            ;;
        3)
            clear
            curl -Lso mirrors https://focal-mirrors.optimizethis.net; sudo bash mirrors
            clear
            main_menu
            ;;
        4)
            clear
            curl -Lso mirrors https://bionic-mirrors.optimizethis.net; sudo bash mirrors
            clear
            main_menu
            ;;
        5)
            clear
            curl -Lso mirrors https://debian-mirrors.optimizethis.net; sudo bash mirrors
            clear
            main_menu
            ;;
        0)
            clear
            main_menu
            ;;
        *)
            echo $red'Wrong option'$clear
            WrongCommand
            ;;
    esac
}

#
# DISPLAY MAIN MENU
#

main_menu()
{
    local answer
echo -ne "
$(ColorGreen '1)')  7-Zip Release v23.01
$(ColorGreen '2)')  cURL, WGET
$(ColorGreen '3)')  CMake, Meson, Ninja, and Golang
$(ColorGreen '4)')  ImageMagick 7
$(ColorGreen '5)')  FFmpeg (This is a large script, be prepared to sit back for a while)
$(ColorGreen '6)')  GParted with all extra packages
$(ColorGreen '7)')  Video Players
$(ColorGreen '8)')  Custom User Scripts
$(ColorGreen '9)') Extra Source Mirrors
$(ColorGreen '10)') APT to Debian Package Downloader
$(ColorGreen '0)')  Exit
$(ColorBlue 'Choose an option:') "
    read answer
    case "$answer" in
        1)
            clear
            szip_release_fn
            clear
            main_menu
            ;;
        2)
            clear
            dl_tools_fn
            clear
            main_menu
            ;;
        3)
            clear
            build_tools_fn
            clear
            main_menu
            ;;
        4)
            clear
            magick_fn
            clear
            main_menu
            ;;
        5)
            clear
            ffmpeg_fn
            clear
            main_menu
            ;;
        6)
            clear
            gparted_fn
            clear
            main_menu
            ;;
        7)
            clear
            video_fn
            clear
            main_menu
            ;;
        8)
            clear
            custom_user_scripts
            clear
            main_menu
            ;;
        9)
            clear
            extra_mirrors
            clear
            main_menu
            ;;
        10)
            clear
            deb_dl_fn
            clear
            main_menu
            ;;
        0)
            sudo rm "$0"
            clear
            exit 0
            ;;
        *)
            echo $red'Wrong option'$clear
            WrongCommand
            ;;
    esac
}

main_menu
