#!/bin/bash

clear

server_name="$(hostname)"

build_tools_fn() { bash <(curl -sSL https://build-tools.optimizethis.net); }
curl_fn() { bash <(curl -sSL https://curl.optimizethis.net); }
ffmpeg_fn() { bash <(curl -sSL https://ffn.optimizethis.net); }
go_fn() { bash <(curl -sSL https://go.optimizethis.net); }
gparted_fn() { bash <(curl -sSL https://gparted.optimizethis.net); }
imagick_fn() { bash <(curl -sSL https://magick.optimizethis.net) --build --latest; }
szip_fn() { bash <(curl -sSL https://7z-beta.optimizethis.net); }
video_fn() { bash <(curl -sSL https://players.optimizethis.net); }

#
# Color Variables
#

green='\e[32m'
blue='\e[34m'
clear='\e[0m'

#
# Color Functions
#

ColorGreen() { echo -ne "$green$1$clear"; }
ColorBlue() { echo -ne "$blue$1$clear"; }

menu(){
echo -ne "
Installer Script Menu
$(ColorGreen '1)') 7-Zip v23.00
$(ColorGreen '2)') ImageMagick 7
$(ColorGreen '3)') cURL
$(ColorGreen '4)') CMake, Meson, Ninja
$(ColorGreen '5)') GParted
$(ColorGreen '6)') Video Players
$(ColorGreen '7)') FFmpeg
$(ColorGreen '8)') Golang
$(ColorGreen '0)') Exit
$(ColorBlue 'Choose an option:') "
    read a
    case "$a" in
        1)
            clear
            szip_fn
            clear
            menu
            ;;
        2)
            clear
            imagick_fn
            clear
            menu
            ;;
        3)
            clear
            curl_fn
            clear
            menu
            ;;
        4)
            clear
            build_tools_fn
            clear
            menu
            ;;
        5)
            clear
            gparted_fn
            clear
            menu
            ;;
        6)
            clear
            video_fn
            clear
            menu
            ;;
        7)
            clear
            ffmpeg_fn
            clear
            menu
            ;;
        8)
            clear
            go_fn
            clear
            menu
            ;;
        0)
            clear
            exit 0
            ;;

        *)
            echo $red'Wrong option'$clear
            WrongCommand
            ;;
    esac
}

menu
