#!/bin/bash

clear

#
# MENU COLOR FUNCTIONS
#

green='\e[32m'
blue='\e[34m'
clear='\e[0m'
ColorGreen()
{
    echo -ne "$green$1$clear"
}
ColorBlue()
{
    echo -ne "$blue$1$clear"
}

#
# SHOW SCRIPT BANNER
#

function box_out_banner()
{
    input_char=$(echo "$@" | wc -c)
    line=$(for i in `seq 0 $input_char`; do printf "-"; done)
    tput bold
    line="$(tput setaf 3)${line}"
    space=${line//-/ }
    echo " ${line}"
    printf '|' ; echo -n "$space" ; printf "%s\n" '|';
    printf '| ' ;tput setaf 4; echo -n "$@"; tput setaf 3 ; printf "%s\n" ' |';
    printf '|' ; echo -n "$space" ; printf "%s\n" '|';
    echo " ${line}"
    tput sgr 0
}
box_out_banner 'Ubuntu Mirror Script'

#
# DETERMINE WHAT DOWNLOADER TO USE
#

if type -P curl &>/dev/null; then
    dl_app='curl -Lso'
else
    dl_app='wget -cqO'
fi

#
# DISPLAY DEBIAN MIRRORS MENU
#

debian_mirrors()
{
    local answer
echo -ne "
$(ColorGreen '1)') Debian 11 - Bullseye
$(ColorGreen '2)') Debian 12 - Bookworm
$(ColorGreen '0)') Back
$(ColorBlue 'Choose the Debian release version:') "
    read answer
    clear
    case "$answer" in
        1)
                $dl_app bullseye-mirrors https://bullseye-mirrors.optimizethis.net; sudo bash bullseye-mirrors
                rm bullseye-mirrors
                clear
                return 0
                ;;
        2)
                $dl_app bookworm-mirrors https://bookworm-mirrors.optimizethis.net; sudo bash bookworm-mirrors
                rm bookworm-mirrors
                clear
                return 0
                ;;
        0)      main_menu;;
        *)      debian_mirrors;;
    esac
}

#
# DISPLAY UBUNTU MIRRORS MENU
#

ubuntu_mirrors()
{
    local answer
echo -ne "
$(ColorGreen '1)') Ubuntu 23.04 - Lunar Lobster
$(ColorGreen '2)') Ubuntu 22.04 - Jammy Jellyfish
$(ColorGreen '3)') Ubuntu 20.04 - Focal Fossa
$(ColorGreen '4)') Ubuntu 18.04 - Bionic Beaver
$(ColorGreen '0)') Back
$(ColorBlue 'Choose the Ubuntu release version:') "
    read answer
    clear
    case "$answer" in
        1)
                $dl_app lunar-mirrors https://lunar-mirrors.optimizethis.net; sudo bash lunar-mirrors
                rm lunar-mirrors
                clear
                return 0
                ;;
        2)
                $dl_app jammy-mirrors https://jammy-mirrors.optimizethis.net; sudo bash jammy-mirrors
                rm jammy-mirrors
                clear
                return 0
                ;;
        3)
                $dl_app focal-mirrors https://focal-mirrors.optimizethis.net; sudo bash focal-mirrors
                rm focal-mirrors
                clear
                return 0
                ;;
        4)
                $dl_app bionic-mirrors https://bionic-mirrors.optimizethis.net; sudo bash bionic-mirrors
                rm bionic-mirrors
                clear
                return 0
                ;;
        0)      main_menu;;
        *)      ubuntu_mirrors;;
    esac
}

#
# DISPLAY THE MAIN MENU
#

main_menu()
{
    local answer
echo -ne "
$(ColorGreen '1)') Ubuntu Mirrors
$(ColorGreen '2)') Debian Mirrors
$(ColorGreen '0)') Exit
$(ColorBlue 'Choose an operating system:') "
    read answer
    clear
    case "$answer" in
        1)      ubuntu_mirrors;;
        2)      debian_mirrors;;
        0)      return 0;;
        *)      main_menu;;
    esac
}

main_menu
