#!/usr/bin/env bash
# shellcheck disable=SC2034,SC2068,SC2086,SC2000,SC2162,SC2317

####################################################################################################################################
##
##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-clang-17
##
##  Purpose: Build LLVM Clang-17
##
##  Updated: 12.03.23
##
##  Script version: 1.3
##
####################################################################################################################################

clear

if [ "${EUID}" -eq '0' ]; then
    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
    exit 1
fi

#
# SET GLOBAL VARIABLES
#

script_ver=1.13
cwd="${PWD}"/clang-17-build-script
install_dir=/usr/local
pc_type=x86_64-linux-gnu
ld_gold_linker="$(sudo find /usr/ -type f -name 'ld.gold' | head -n1)"
user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
web_repo=https://github.com/slyfox1186/script-repo
debug=OFF # CHANGE THIS VARIABLE TO "ON" FOR HELP WITH TROUBLESHOOTING UNEXPECTED ISSUES DURING THE BUILD

#
# CREATE OUTPUT DIRECTORIES
#

if [ -d "${cwd}"/llvm-17.0.6 ]; then
    sudo rm -fr "${cwd}"/llvm-17.0.6
fi
mkdir -p "${cwd}"

#
# SET THE CC/CXX COMPILERS & THE COMPILER OPTIMIZATION FLAGS
#

CC=clang
CXX=clang++
CFLAGS='-g -O3 -fPIC -march=native'
CXXFLAGS="${CFLAGS}"
export CC CXX CFLAGS CXXFLAGS

#
# SET THE PATH VARIABLE
#

PATH="\
/usr/lib/ccache/bin:\
/usr/lib/ccache:\
${HOME}/.cargo/bin:\
${HOME}/.local/bin:\
/usr/local/sbin:\
/usr/local/cuda/bin:\
/usr/local/bin:\
/usr/sbin:\
/usr/bin:\
/sbin:\
/bin:\
/snap/bin\
"
export PATH

#
# SET THE PKG_CONFIG_PATH VARIABLE
#

PKG_CONFIG_PATH="\
/usr/share/pkgconfig:\
/usr/local/lib/x86_64-linux-gnu/pkgconfig:\
/usr/local/lib/pkgconfig:\
/usr/lib/x86_64-linux-gnu/pkgconfig:\
/usr/lib/pkgconfig:\
/lib/pkgconfig\
"
export PKG_CONFIG_PATH

#
# CREATE FUNCTIONS
#

exit_fn()
{
    printf "\n%s\n\n%s\n%s\n\n"                                    \
        'The script has completed'                                \
        'Make sure to star this repository to show your support!' \
        "${web_repo}"
    exit 0
}

fail_fn()
{
    printf "\n\n%s\n\n%s\n\n%s\n\n"      \
        "${1}"                           \
        'To report a bug please visit: ' \
        "${web_repo}/issues"
    exit 1
}

cleanup_fn()
{
    local choice

    printf "%s\n\n%s\n%s\n\n"                    \
        'Do you want to remove the build files?' \
        '[1] Yes'                                \
        '[2] No'
    read -p 'Your choices are (1 or 2): ' choice

    case "${choice}" in
        1)      sudo rm -fr "${cwd}";;
        2)      clear;;
        *)
                clear
                printf "%s\n\n" 'Error: bad user input. Reverting script...'
                sleep 3
                unset choice
                clear
                cleanup_fn
                ;;
    esac
}

show_ver_fn()
{
    printf "%s\n\n" 'The installed clang version is:'

    if [ -f "${install_dir}"/bin/clang-17 ]; then
        printf "%s\n" 'clang-17:'
        "${install_dir}"/bin/clang-17 --version
        echo
    fi

    if [ -f "${install_dir}"/bin/clang++-17 ]; then
        printf "%s\n" 'clang++-17:'
        "${install_dir}"/bin/clang++-17 --version
        echo
    elif [ -f "${install_dir}"/bin/clang++ ]; then
        printf "%s\n" 'clang-++:'
        "${install_dir}"/bin/clang++ --version
        echo
    fi
}
show_ver_fn
exit

execute()
{
    echo "$ ${*}"

    if [ "${debug}" = 'ON' ]; then
        if ! output="$("${@}")"; then
            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
            fail_fn "Failed to execute: ${*}"
        fi
    else
        if ! output="$("${@}" 2>&1)"; then
            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
            fail_fn "Failed to execute: ${*}"
        fi
    fi
}

build()
{
    printf "\n%s\n%s\n" \
        "Building ${1} - version ${2}" \
        '=========================================='

    if [ -f "${cwd}/${1}.done" ]; then
        if grep -Fx "${2}" "${cwd}/${1}.done" >/dev/null; then
            echo "${1} version ${2} already built. Remove ${cwd}/${1}.done lockfile to rebuild it."
            return 1
        fi
    fi
    return 0
}

build_done() { echo "${2}" > "${cwd}/${1}.done"; }

download()
{
    dl_path="${cwd}"
    dl_url="${1}"
    dl_file="${2:-"${1##*/}"}"

    if [[ "${dl_file}" =~ tar. ]]; then
        output_dir="${dl_file%.*}"
        output_dir="${3:-"${output_dir%.*}"}"
    else
        output_dir="${3:-"${dl_file%.*}"}"
    fi

    target_file="${dl_path}/${dl_file}"
    target_dir="${dl_path}/${output_dir}"

    if [ -f "${target_file}" ]; then
        echo "The file \"${dl_file}\" is already downloaded."
    else
        printf "%s\n\n" "Downloading \"${dl_url}\" saving as \"${dl_file}\""
        if ! wget --show-progress -U "${user_agent}" -cqO "${target_file}" "${dl_url}"; then
            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
            sleep 10
            if ! wget --show-progress -U "${user_agent}" -cqO "${target_file}" "${dl_url}"; then
                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit. Line: ${LINENO}"
            fi
        fi
        printf "\n%s\n\n" 'Download completed'
    fi

    if [ -d "${target_dir}" ]; then
        sudo rm -fr "${target_dir}"
    fi

    mkdir -p "${target_dir}"

    if [ -n "${3}" ]; then
        if ! tar -zxf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
            sudo rm "${target_file}"
            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
        fi
    else
        if ! tar -zxf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
            sudo rm "${target_file}"
            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script. Line: ${LINENO}"
        fi
    fi

    printf "%s\n\n" "File extracted: ${dl_file}"

    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
}

git_1_fn()
{
    local curl_cmd github_repo github_url

    github_repo="${1}"
    github_url="${2}"

    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
        g_ver="$(echo "${curl_cmd}" | jq -r '.[1].name' 2>/dev/null)"
        g_url="$(echo "${curl_cmd}" | jq -r '.[1].tarball_url' 2>/dev/null)"
        g_ver="${g_ver#llvmorg-}"
    fi
}

git_ver_fn()
{
    local t_flag v_flag v_url

    v_url="${1}"
    v_flag="${2}"

    case "${v_flag}" in
            R)      t_flag=releases;;
            T)      t_flag=tags;;
    esac

    git_1_fn "${v_url}" "${t_flag}" 2>/dev/null
}

#
# PRINT THE OPTIONS AVAILABLE WHEN MANUALLY RUNNING THE SCRIPT
#

# GET THE HIGHEST VERSION AVAILABLE ON APT FOR THE PACKAGE libstdc++
get_libstdc="$(sudo apt list 'libstdc++-*-dev' 2>/dev/null | grep -Eo '^libstdc\+\+-[0-9]{2}-dev' | sort -r | head -n1)"

pkgs=(autoconf autoconf-archive automake autopoint binutils binutils-dev bison
      build-essential ccache clang clang-15 cmake curl doxygen jq libc6 libc6-dev
      libedit-dev libllvm-ocaml-dev libllvm-ocaml-15-dev libtool libtool-bin libxml2-dev
      m4 nasm ninja-build yasm zlib1g-dev wget "${get_libstdc}")

for  pkg in ${pkgs[@]}
do
    missing_pkg="$(sudo dpkg -l | grep -o "${pkg}")"

    if [ -z "${missing_pkg}" ]; then
        missing_pkgs+=" ${pkg}"
    fi
done

if [ -n "${missing_pkgs}" ]; then
    sudo apt -y install ${missing_pkgs}
    clear
else
    printf "%s\n" 'The APT packages are already installed'
fi

#
# INSTALL BINUTILS TO ENABLE THE "GOLD" LD LINKER OPTION
#

if [ ! -f '/usr/local/bin/ld.gold' ]; then
    bash <(curl -A "${user_agent}" -sSL 'https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Installer%20Scripts/GNU%20Software/build-binutils')
fi

#
# ADD ADDITIONAL LIBRARY SEARCH PATHS TO THE LD LINKER AND THEN ACTIVATE THE CHANGES 
#

sudo bash -c 'bash <(curl -sSL https://ld-linker.optimizethis.net)'
sudo ldconfig -v

#
# BEGIN BUILDING CLANG
#

clear
box_out_banner()
{
    input_char=$(echo "${@}" | wc -c)
    line=$(for i in $(seq 0 ${input_char}); do printf '-'; done)
    tput bold
    line="$(tput setaf 3)${line}"
    space=${line//-/ }
    echo " ${line}"
    printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
    printf '| ' ;tput setaf 4; echo -n "${@}"; tput setaf 3 ; printf "%s\n" ' |';
    printf '|' ; echo -n "${space}" ; printf "%s\n" '|';
    echo " ${line}"
    tput sgr 0
}
box_out_banner "Clang-17 Build Script - version ${script_ver}"

git_ver_fn 'llvm/llvm-project' 'T'
if build 'llvm' "${g_ver}"; then
    download "${g_url}" "llvm-${g_ver}.tar.gz"
    project_pkgs='clang;clang-tools-extra;lld'
    runtime_pkgs='libunwind;libcxxabi;libcxx;openmp'
    cmake -S llvm -B build                                                            \
          -DCMAKE_install_dir="${install_dir}"                                     \
          -DCMAKE_BUILD_TYPE=Release                                                  \
          -DLLVM_LOCAL_RPATH="${install_dir}"/lib                                     \
          -DBUILD_SHARED_LIBS=OFF                                                     \
          -DLLVM_ENABLE_LTO=OFF                                                       \
          -DBENCHMARK_ENABLE_LTO=OFF                                                  \
          -DCLANG_TOOL_CLANG_CHECK_BUILD=ON                                           \
          -DCLANGD_TIDY_CHECKS=OFF                                                    \
          -DLLVM_BUILD_TOOLS=ON                                                       \
          -DBENCHMARK_USE_BUNDLED_GTEST=OFF                                           \
          -DLLVM_THINLTO_CACHE_PATH="${install_dir}"/lto.cache                        \
          -DCCACHE_PROGRAM="$(type -P ccache)"                                        \
          -DCMAKE_C_COMPILER="${CC}"                                                  \
          -DCMAKE_CXX_COMPILER="${CXX}"                                               \
          -DCMAKE_C_FLAGS="${CFLAGS}"                                                 \
          -DCMAKE_CXX_FLAGS="${CXXFLAGS}"                                             \
          -DCMAKE_CXX_STANDARD=17                                                     \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=OFF                                         \
          -DCMAKE_INSTALL_PACKAGEDIR=lib/cmake                                        \
          -DCMAKE_INSTALL_RUNSTATEDIR="${install_dir}/lib:$ORIGIN"                    \
          -DCMAKE_LINKER="${ld_gold_linker}"                                          \
          -DGOLD_EXECUTABLE="${ld_gold_linker}"                                       \
          -DCPACK_BINARY_DEB=ON                                                       \
          -DCPACK_SOURCE_ZIP=ON                                                       \
          -DLIBCLANG_BUILD_STATIC=ON                                                  \
          -DLLVM_CCACHE_BUILD=ON                                                      \
          -DLLVM_CCACHE_DIR="${HOME}"/.ccache                                         \
          -DLLVM_DEFAULT_TARGET_TRIPLE="${pc_type}"                                   \
          -DLLVM_ENABLE_CURL=ON                                                       \
          -DLLVM_ENABLE_PROJECTS="${project_pkgs}"                                    \
          -DLLVM_ENABLE_RUNTIMES="${runtime_pkgs}"                                    \
          -DLLVM_BUILD_RUNTIME=ON                                                     \
          -DLLVM_BUILD_RUNTIMES=ON                                                    \
          -DLLVM_ENABLE_WARNINGS=OFF                                                  \
          -DLLVM_ENABLE_ZLIB=ON                                                       \
          -DLLVM_ENABLE_ZSTD=ON                                                       \
          -DLLVM_INCLUDE_DOCS=OFF                                                     \
          -DLLVM_INCLUDE_EXAMPLES=OFF                                                 \
          -DLLVM_TARGETS_TO_BUILD=all                                                 \
          -DLLVM_TOOL_{CLANG,GOLD,LIBCXX,LIBCXXABI,LIBUNWIND,LLD}_BUILD=ON            \
          -DLLVM_TOOL_LIBC_BUILD=OFF                                                  \
          -DLLVM_USE_STATIC_ZSTD=OFF                                                  \
          -G Ninja -Wno-Dev
    echo
    if ! ninja "-j$(nproc --all)" -C build; then
        printf "\n%s\n\n" "Failed to execute the command: ninja -j$(nproc --all) -C build. Line ${LINENO}"
        exit 1
    fi
    echo
    if ! sudo ninja -C build install; then
        printf "\n%s\n\n" "Failed to execute the command: sudo ninja -C build install. Line ${LINENO}"
        exit 1
    fi
fi

# SHOW THE NEWLY INSTALLED MAGICK VERSION
show_ver_fn

# PROMPT THE USER TO CLEAN UP THE BUILD FILES
cleanup_fn

# SHOW EXIT MESSAGE
exit_fn
