#!/usr/bin/env bash
# shellcheck disable=SC2162,SC2317

###########################################################################################################
##
##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-clang-18
##
##  Purpose: Build LLVM-18
##
##  Updated: 09.08.23
##
##  Script version: 1.0
##
###########################################################################################################

clear

if [ "${EUID}" -eq '0' ]; then
    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
    exit 1
fi

#
# SET VARIABLES
#

script_ver=1.1
git_dir=llvm-project-18.0.0
git_url=https://github.com/llvm/llvm-project.git
cwd="$PWD"/llvm18-build-script
install_dir=/usr/local
web_repo=https://github.com/slyfox1186/script-repo

list1='clang;clang-tools-extra;openmp'
list2='libcxx;libcxxabi;libunwind;compiler-rt'

printf "\n%s\n%s\n\n" \
    "LLVM Build Script - v${script_ver}" \
    '==============================================='

#
# CREATE OUTPUT DIRECTORY
#

if [ -d "$cwd" ]; then
    sudo rm -fr "$cwd"
fi
mkdir -p "$cwd"

#
# SET THE C+CPP COMPILERS
#

export CC=clang CXX=clang++

#
# EXPORT COMPILER OPTIMIZATION FLAGS
#

export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'

#
# SET THE PATH VARIABLE
#

PATH="\
/usr/lib/ccache:\
${HOME}/perl5/bin:\
${HOME}/.cargo/bin:\
${HOME}/.local/bin:\
/usr/local/sbin:\
/usr/local/cuda/bin:\
/usr/local/x86_64-linux-gnu/bin:\
/usr/local/bin:\
/usr/sbin:\
/usr/bin:\
/sbin:\
/bin:\
/usr/local/games:\
/usr/games:\
/snap/bin\
"
export PATH

#
# SET THE PKG_CONFIG_PATH VARIABLE
#

PKG_CONFIG_PATH="\
/usr/local/lib64/pkgconfig:\
/usr/local/lib/pkgconfig:\
/usr/local/lib/x86_64-linux-gnu/pkgconfig:\
/usr/local/share/pkgconfig:\
/usr/lib64/pkgconfig:\
/usr/lib/pkgconfig:\
/usr/lib/x86_64-linux-gnu/pkgconfig:\
/usr/share/pkgconfig:\
/lib64/pkgconfig:\
/lib/pkgconfig:\
/lib/x86_64-linux-gnu/pkgconfig\
"
export PKG_CONFIG_PATH

#
# CREATE FUNCTIONS
#

exit_fn()
{
    printf "\n%s\n\n%s\n\n" \
        'Make sure to star this repository to show your support!' \
        "$web_repo"
    exit 0
}

fail_fn()
{
    printf "\n%s\n\n%s\n\n" \
        "$1" \
        "To report a bug create an issue at: $web_repo/issues"
    exit 1
}

cleanup_fn()
{
    local choice

    printf "%s\n%s\n%s\n\n%s\n%s\n\n" \
        '============================================' \
        '  Do you want to clean up the build files?  ' \
        '============================================' \
        '[1] Yes' \
        '[2] No'
    read -p 'Your choices are (1 or 2): ' choice

    case "${choice}" in
        1)      sudo rm -fr "$cwd";;
        2)      echo;;
        *)
                clear
                printf "%s\n\n" 'Bad user input. Reverting script...'
                sleep 3
                unset choice
                clear
                cleanup_fn
                ;;
    esac
}

#
# INSTALL REQUIRED APT PACKAGES
#

pkgs_fn()
{
    pkgs=(autoconf autoconf-archive autogen automake build-essential ccache
          cmake curl git jq libtool libtool-bin lzip m4 pkg-config)

    for i in ${pkgs[@]}
    do
        missing_pkg="$(sudo dpkg -l | grep -o "${i}")"

        if [ -z "${missing_pkg}" ]; then
            missing_pkgs+=" ${i}"
        fi
    done

    if [ -n "${missing_pkgs}" ]; then
        sudo apt install ${missing_pkgs}
        sudo apt -y autoremove
        clear
    fi
}

#
# DOWNLOAD THE ARCHIVE FILE
#

cd "$cwd" || exit 1

if [ ! -d llvm-project ]; then
    git clone --depth=1 "${git_url}" "${git_dir}"
fi

#
# BUILD PROGRAM FROM SOURCE
#

cd "${git_dir}" || exit 1

mkdir build
cd build || exit 1
cmake -S ../llvm                     \
-G Ninja -Wno-dev                    \
-DCMAKE_INSTALL_DIR="$install_dir" \
-DCMAKE_BUILD_TYPE=Release           \
-DCMAKE_C_COMPILER=gcc               \
-DCMAKE_CXX_COMPILER=g++             \
-DLLVM_TARGETS_TO_BUILD=host         \
-DLLVM_ENABLE_PROJECTS="${list1}"    \
-DLLVM_ENABLE_RUNTIMES="${list2}"
ninja "-j$(nproc --all)"
if ! sudo ninja "-j$(nproc --all)" install; then
    fail_fn "Failed to execute: sudo ninja -j$(nproc --all) install:Line ${LINENO}"
    exit 1
fi

# PROMPT USER TO CLEAN UP FILES
cleanup_fn
# SHOW EXIT MESSAGE
exit_fn
