#!/usr/bin/env bash

clear

cwd="$PWD"/git-installers
repo=https://github.com/slyfox1186/script-repo

if [ ! -d "$cwd"/completed ]; then
    mkdir -p "$cwd"/completed
fi

exit_fn()
{
    printf "\n%s\n\n%s\n\n" \
        'Make sure to star this repository to show your support!' \
        "$repo"
    exit 0
}

fail_fn()
{
    printf "\n%s\n\n%s\n\n" \
        "$1" \
        "To report a bug create an issue at: $repo/issues"
    exit 1
}

cleanup_fn()
{
    local answer

    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
        '============================================' \
        '  Do you want to clean up the build files?  ' \
        '============================================' \
        '[1] Yes' \
        '[2] No'
    read -p 'Your choices are (1 or 2): ' answer

    case "$answer" in
        1)      sudo rm -fr "$cwd" "$0";;
        2)      echo;;
        *)
                printf "\n%s\n\n" 'Bad user input.'
                read -p 'Press enter to try again.'
                echo
                cleanup_fn
                ;;
    esac
}

pkgs=(asciidoc autogen autoconf automake binutils bison build-essential bzip2 ccache cmake
      curl libc6-dev libintl-perl libpth-dev libtool libtool-bin lzip lzma-dev m4 meson
      nasm ninja-build texinfo xmlto yasm zlib1g-dev)

for i in ${pkgs[@]}
do
    missing_pkg="$(dpkg -l | grep -o "${i}")"

    if [ -z "$missing_pkg" ]; then
        missing_pkgs+=" $i"
    fi
done

if [ -n "$missing_pkgs" ]; then
    sudo apt -y install $missing_pkgs
    sudo apt -y autoremove
    clear
fi

install_fn()
{
    local i scripts
    clear

    scripts="$(ls | sort -n)"

    for i in ${scripts[@]} 
    do
        if [ -f "$i" ]; then
            if bash "$i"; then
                sudo find . -maxdepth 1 -type f -name "$i" -exec mv {} completed \;
                printf "\n%s\n\n" "Script finished: $i"
            else
                fail_fn "Failed to install: $i"
            fi
            sleep 2
        fi
    done
}

install_choice_fn()
{
    printf "%s\n\n%s\n%s\n\n" \
        'Do you want to install all of the scripts now?' \
        '[1] Yes' \
        '[2] No'
    read -p 'Your choices are (1 or 2): ' answer

    case "$answer" in
        1)      install_fn;;
        2)      clear;;
        *)
                printf "%s\n\n" 'Bad user input... Resetting script.'
                sleep 3
                unset answer
                clear
                install_choice_fn
    esac
}

dl_fn()
{
    if [ ! -f "$1" ]; then
        wget --show-progress -cqO "$1" "$2"
    fi
}

cd "$cwd" || exit 1

main_url='https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Installer%20Scripts/GitHub%20Projects'

dl_fn '01-build-zlib' "$main_url/build-zlib"
dl_fn '02-build-zstd' "$main_url/build-zstd"
dl_fn '03-build-nasm' "$main_url/build-nasm"
dl_fn '04-build-yasm' "$main_url/build-yasm"
dl_fn '05-build-xml2' "$main_url/build-xml2"
dl_fn '06-build-openssl' "$main_url/build-openssl"
dl_fn '07-build-tools' "$main_url/build-tools"
dl_fn '08-build-libpng' "$main_url/build-libpng"
dl_fn '09-build-brotli' "$main_url/build-brotli"
dl_fn '10-build-aria2' "$main_url/build-aria2"
dl_fn '11-build-eog' "$main_url/build-eog"

# DOWNLOAD ALL SCRIPTS
dl_fn
echo

# ASK THE USER IF THEY WANT TO INSTALL ALL OF THE SCRIPTS
install_choice_fn

# CLEANUP THE FILES
cleanup_fn

# SHOW EXIT MESSAGE
exit_fn
