#!/usr/bin/env bash
# shellcheck disable=SC2162,SC2317

#################################################################################################################################
##
##  GitHub Script: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-python3
##
##  Purpose: Install Python3 v3.12.0rc3 from the source code released by the official website: https://www.python.org/downloads
##
##  Features: Static build, OpenSSL backend
##
##  Updated: 10.10.23
##
##  Upgraded to version: 3.12.0
##
##  Added: Debian 10 Bullseye support
##
##  Script version: 1.9
##
#################################################################################################################################

clear

if [ "${EUID}" -eq '0' ]; then
    printf "%s\n\n" 'You must run this script WITHOUT root/sudo.'
    exit 1
fi

#
# SET THE SCRIPT VARIABLES
#

script_ver=1.9
py_ver=3.12.0
archive_dir=Python-${py_ver}.tar.xz
archive_url=https://www.python.org/ftp/python/3.12.0/${archive_dir}
archive_ext="${archive_url//*.}"
archive_name="${archive_dir}.tar.${archive_ext}"
cwd="${PWD}"/python3-build-script
user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36'
web_repo=https://github.com/slyfox1186/script-repo

#
# START THE PYTHON3 BUILD
#

printf "%s\n%s\n\n" \
    "Python3 Build Script v${py_ver} - v${script_ver}" \
    '==============================================='

#
# CREATE THE OUTPUT DIRECTORY
#

if [ -d "${cwd}" ]; then
    sudo rm -fr "${cwd}"
fi
mkdir -p "${cwd}"

#
# SET THE C & CPP COMPILERS
#

export CC=gcc CXX=g++

#
# SET THE COMPILER OPTIMIZATION FLAGS
#

LDFLAGS='-L/lib/"${install_dir}" -L/usr/lib/"${install_dir}" -L/usr/local/lib'
LDFLAGS+=' -L/usr/local/lib64 -L/usr/lib64 -L/usr/lib -L/lib64 -L/lib'

export CXXFLAGS='-g -O2 -march=native'
export CFLAGS="-I/usr/include/openssl ${CXXFLAGS}"
export CPPFLAGS='-I/usr/include/openssl -I/usr/local/include -I/usr/include'
export CFLAGS CXXFLAGS LDFLAGS

#
# SET THE PATH VARIABLE
#

PATH="\
/usr/lib/ccache:\
${HOME}/.cargo/bin:\
${HOME}/.local/bin:\
/usr/local/sbin:\
/usr/local/bin:\
/usr/sbin:\
/usr/bin:\
/sbin:\
/bin:\
/usr/local/cuda/bin:\
/snap/bin\
"
export PATH

#
# SET THE PKG_CONFIG_PATH VARIABLE
#

PKG_CONFIG_PATH="\
/usr/local/lib64/pkgconfig:\
/usr/local/lib/pkgconfig:\
/usr/local/lib/usr/local/pkgconfig:\
/usr/local/share/pkgconfig:\
/usr/lib64/pkgconfig:\
/usr/lib/pkgconfig:\
/usr/lib/usr/local/pkgconfig:\
/usr/share/pkgconfig:\
/lib64/pkgconfig:\
/lib/pkgconfig:\
/lib/usr/local/pkgconfig\
"
export PKG_CONFIG_PATH

#
# SET THE LD_LIBRARY_PATH VARIABLE
#

cuda_lib_dir="$(find /usr/local/cuda* -type d -name lib64 | head -n1)"

if [ -n "${cuda_lib_dir}" ]; then
LD_LIBRARY_PATH="\
/usr/local/lib64/:\
/usr/local/lib/:\
/usr/lib64/:\
/usr/lib/:\
lib64/:\
lib/:\
${cuda_lib_dir}/\
"
export LD_LIBRARY_PATH
else
LD_LIBRARY_PATH="\
/usr/local/lib64/:\
/usr/local/lib/:\
/usr/lib64/:\
/usr/lib/:\
lib64/:\
lib/\
"
export LD_LIBRARY_PATH
fi

#
# CREATE FUNCTIONS
#

exit_fn()
{
    printf "\n%s\n\n%s\n%s\n\n" \
        'The script has completed!' \
        'Make sure to star this repository to show your support!' \
        "${web_repo}"
    exit 0
}

fail_fn()
{
    printf "\n\n%s\n\n%s\n\n%s\n\n" \
        "${1}" \
        'Please create a support ticket so I can work on a fix.' \
        "${web_repo}/issues"
    exit 1
}

show_ver_fn()
{
    save_ver="$(sudo find /usr/local -type f -name python3.12 | grep -Eo '[0-9\.]+$')"
    printf "\n%s\n\n" "The installed Python3 version is: ${save_ver}"
    sleep 3
}

cleanup_fn()
{
    local answer
    clear

    printf "\n%s\n\n%s\n%s\n\n" \
        'Do you want to remove the build files?' \
        '[1] Yes' \
        '[2] No'
    read -p 'Your choices are (1 or 2): ' answer

    case "${answer}" in
        1)      sudo rm -fr "${cwd}" "${0}";;
        2)      return 0;;
        *)
                clear
                printf "%s\n\n" 'Bad user input. Resetting script...'
                sleep 3
                unset answer
                cleanup_fn
                ;;
    esac
}

installed() { return $(dpkg-query -W -f '${Status}\n' "${1}" 2>&1 | awk '/ok installed/{print 0;exit}{print 1}'); }

pkgs=(autoconf autoconf-archive autogen automake binutils build-essential ccache cmake
      curl git itstool libb2-dev libexempi-dev libgnome-desktop-3-dev libhandy-1-dev
      libpeas-dev libpeasd-3-dev libssl-dev libtool libtool-bin m4 meson nasm ninja-build
      openssl python3 valgrind yasm zlib1g-dev)

for pkg in ${pkgs[@]}
do
    if ! installed "${pkg}"; then
        missing_pkgs+=" ${pkg}"
    fi
done

if [ -n "${missing_pkgs}" ]; then
    echo '$ Installing missing packages'
    echo
    for i in "${missing_pkgs}"
        do
            if ! sudo apt -y install $i; then
                fail_fn "Failed to install the apt packages. Line: ${LINENO}"
            fi
        done
else
    echo '$ The packages are already installed.'
    echo
fi

#
# INSTALL REQUIRED APT PACKAGES
#

install_libportal_fn()
{
    if ! wget --show-progress -U "${user_agent}" -cq 'https://github.com/flatpak/libportal/releases/download/0.7.1/libportal-0.7.1.tar.xz'; then
        clear
        printf "%s\n\n" "Failed to download the libportal archive file. Line: ${LINENO}"
        exit 1
    fi
    mkdir libportal-0.7.1
    tar -xf libportal-0.7.1.tar.xz -C libportal-0.7.1 --strip-components 1
    cd libportal-0.7.1 || exit 1
    meson setup build --prefix=/usr/local      \
                      --buildtype=release      \
                      --default-library=static \
                      --strip                  \
                      -Dc_args="${CFLAGS}"     \
                      -Dcpp_args="${CXXFLAGS}"
    ninja "-j$(nproc --all)" -C build
    sudo ninja "-j$(nproc --all)" -C build install
}

debian_os_version()
{
    case "${VER}" in
        trixie|12)      pkgs_fn 'libgnome-desktop-4-dev libportal-dev libportal-gtk3-dev libportal-gtk4-dev';;
        10|11)
                        pkgs_fn 'libgnome-desktop-3-dev'
                        install_libportal_fn
                        ;;
        *)              fail_fn "Could not detect the Debian version. Line: ${LINENO}";;
    esac
}

#
# TEST THE OS AND ITS VERSION IF UBUNTU THEN CALL THE pkgs_fn
#

find_lsb_release="$(sudo find /usr -type f -name 'lsb_release')"

if [ -f /etc/os-release ]; then
    source /etc/os-release
    OS_TMP="$NAME"
    VER_TMP="$VERSION_ID"
    CODENAME="$VERSION_CODENAME"
    OS="$(echo "${OS_TMP}" | awk '{print $1}')"
    VER="$(echo "${VER_TMP}" | awk '{print $1}')"
elif [ -n "${find_lsb_release}" ]; then
    OS="$(lsb_release -d | awk '{print $2}')"
    VER="$(lsb_release -r | awk '{print $2}')"
else
    fail_fn "Failed to define the \$OS and/or \$VER variables. Line: ${LINENO}"
fi

if [ -z "${VER}" ]; then
    VER="${CODENAME}"
fi

case "${OS}" in
    Debian|n/a)         debian_os_version;;
    Ubuntu)             pkgs_fn;;
    *)                  fail_fn "Could not detect the OS architecture. Line: ${LINENO}";
esac

#
# DOWNLOAD THE ARCHIVE FILE
#

if [ ! -f "${cwd}/${archive_name}" ]; then
    curl -A "${user_agent}" -Lso "${cwd}/${archive_name}" "${archive_url}"
fi

#
# CREATE THE OUTPUT DIRECTORY
#

if [ -d "${cwd}/${archive_dir}" ]; then
    sudo rm -fr "${cwd}/${archive_dir}"
fi
mkdir -p "${cwd}/${archive_dir}/build"

#
# EXTRACT THE ARCHIVE FILES
#

if ! tar -xf "${cwd}/${archive_name}" -C "${cwd}/${archive_dir}" --strip-components 1; then
    fail_fn "Failed to extract: ${cwd}/${archive_name}. Line: ${LINENO}"
    exit 1
fi

#
# LOCATE THE OPENSSL DIR
#

case "$(type -P openssl)" in
    /usr/local/bin/openssl)     openssl_dir=/usr/local;;
    /usr/bin/openssl)           openssl_dir=/usr;;
    *)                          fail_fn "Failed to locate openssl. Please install it before running the script again. Line: {LINENO}";;
esac

#
# BUILD THE PROGRAM FROM SOURCE CODE
#

cd "${cwd}/${archive_dir}/build" || exit 1
../configure --enable-optimizations               \
             --with-ensurepip=upgrade             \
             --with-lto=yes                       \
             --with-openssl-rpath=auto            \
             --with-openssl="${openssl_dir}"      \
             --with-pkg-config=yes                \
             --with-ssl-default-suites=openssl    \
             --with-valgrind                      \
             PKG_CONFIG="$(type -P pkg-config)"   \
             PKG_CONFIG_PATH="${PKG_CONFIG_PATH}" \
             CFLAGS="${CFLAGS}"                   \
             CPPFLAGS="${CPPFLAGS}"               \
             LDFLAGS="${LDFLAGS}"                 \
             LIBS="$(pkg-config --libs openssl)"
if ! make "-j$(nproc --all)"; then
    fail_fn "Failed to execute: make -j$(nproc --all). Line: ${LINENO}"
    exit 1
fi
if ! sudo make altinstall; then
    fail_fn "Failed to execute: sudo make altinstall. Line: ${LINENO}"
    exit 1
fi

# SHOW THE NEW VERSION
show_ver_fn

# PROMPT THE USER TO CLEAN UP THE BUILD FILES
cleanup_fn

# SHOW THE EXIT MESSAGE
exit_fn
