#!/usr/bin/env bash
# shellcheck disable=SC2162,SC2317

########################################################################################################################
##
##  GitHub: https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/GitHub%20Projects/build-tools
##
##  Purpose: Install the latest versions of: CMake, Ninja, Meson, & Golang
##
##  Updated:
##           - Script date: 11.23.23
##           - Script version: 2.7
##           - Golang version: 1.21.4
##
##  GitHub: https://github.com/slyfox1186/script-repo/edit/main/shell/installers/build-tools
##
##  Supported OS:
##                - ArchLinux 2023.10.14
##                - Debian 10/11/12
##                - Ubuntu (20/22/23).04
##
##  Added: A debug variable to help with troubleshooting issues.
##  Added: Build CMake GUI code
##
########################################################################################################################

clear

if [ "${EUID}" -eq '0' ]; then
    printf "%s\n\n" 'You must run this script WITHOUT root/sudo'
    exit 1
fi

#
# CREATE SCRIPT VARIABLES
#

script_ver=2.6
cwd="${PWD}"/build-tools-script
install_dir=/usr/local
user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
web_repo=https://github.com/slyfox1186/script-repo
latest=false
debug=OFF # CHANGE THE DEBUG VARIABLE TO "ON" FOR HELP TROUBLESHOOTING ISSUES

#
# PRINT SCRIPT BANNER
#

printf "%s\n%s\n"                        \
    "Build-tools script: v${script_ver}" \
    '===================================='
sleep 2

#
# GET CPU CORE COUNT FOR PARALLEL PROCESSING
#

if [ -f /proc/cpuinfo ]; then
    cpu_threads="$(grep --count ^processor /proc/cpuinfo)"
else
    cpu_threads="$(nproc --all)"
fi

#
# CREATE OUTPUT DIRECTORIES
#

mkdir -p "${cwd}"

#
# SET THE C + CPP COMPILERS
#

export CC=gcc CXX=g++

#
# SET COMPILER OPTIMIZATION FLAGS
#

export {CFLAGS,CXXFLAGS}='-g -O3 -pipe -march=native'
export CPPFLAGS='-I/usr/local/include -I/usr/include'

#
# MAKE SURE WE USE THE CORRECT M4 FOLDER
#

aclocal_dir="$(sudo find /usr -type d -name 'aclocal' | sort | head -n1)"

export ACLOCAL_PATH="${aclocal_dir}"

#
# SET THE PATH VARIABLE
#

PATH="\
/usr/lib/ccache/bin:\
/usr/lib/ccache:\
${HOME}/.cargo/bin:\
${HOME}/.local/bin:\
${HOME}/.local/lib/python3.11/site-cwd:\
/home/jman/.local/lib/python3.11/site-cwd:\
/usr/local/cuda/bin:\
/usr/local/sbin:\
/usr/local/bin:\
/usr/sbin:\
/usr/bin:\
/sbin:\
/bin:\
/snap/bin\
"
export PATH

#
# SET THE PKG_CONFIG_PATH VARIABLE
#

PKG_CONFIG_PATH="\
/usr/local/lib64/pkgconfig:\
/usr/local/lib/pkgconfig:\
/usr/local/lib/usr/local/pkgconfig:\
/usr/local/share/pkgconfig:\
/usr/lib64/pkgconfig:\
/usr/lib/pkgconfig:\
/usr/lib/usr/local/pkgconfig:\
/usr/share/pkgconfig:\
/lib64/pkgconfig:\
/lib/pkgconfig:\
/lib/usr/local/pkgconfig\
"
export PKG_CONFIG_PATH

#
# CREATE FUNCTIONS
#

exit_fn()
{
    printf "\n%s\n\n%s\n%s\n\n"                                   \
        'The script has completed'                                \
        'Make sure to star this repository to show your support!' \
        "${web_repo}"
    exit 0
}

fail_fn()
{
    printf "\n\n%s\n\n%s\n\n%s\n\n"                  \
        "${1}"                                       \
        'To report a bug please create an issue at:' \
        "${web_repo}/issues"
    exit 1
}

cleanup_fn()
{
    local answer

    printf "\n%s\n\n%s\n%s\n\n"                  \
        'Do you want to remove the build files?' \
        '[1] Yes'                                \
        '[2] No'
    read -p 'Your choices are (1 or 2): ' answer

    case "${answer}" in
        1)      sudo rm -fr "${cwd}";;
        2)      return 0;;
        *)
                unset answer
                clear
                cleanup_fn
                ;;
    esac
}

show_versions_fn()
{
    local show_cmake_ver show_ninja_ver show_meson_ver
    clear

    show_cmake_ver="$(cmake --version | sed -e 's/cmake version //g' -e 's/CMake suite maintained and supported by Kitware (kitware.com\/cmake).//g' | xargs -n1)"
    show_ninja_ver="$(ninja --version)"
    show_meson_ver="$(meson --version)"
    show_go_ver="$(go version | grep -Eo '[0-9\.]+ | xargs -n1')"

        printf "%s\n\n%s\n%s\n%s\n%s\n" \
            'The updated versions are:' \
            "CMake:  ${show_cmake_ver}" \
            "Ninja:  ${show_ninja_ver}" \
            "Meson:  ${show_meson_ver}" \
            "GoLang: ${show_go_ver}"
}

execute()
{
    echo "$ ${*}"

    if [ "${debug}" = 'ON' ]; then
        if ! output="$("${@}")"; then
            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
            fail_fn "Failed to execute: ${*}"
        fi
    else
        if ! output="$("${@}" 2>&1)"; then
            notify-send -t 5000 "Failed to execute: ${*}" 2>/dev/null
            fail_fn "Failed to execute: ${*}"
        fi
    fi
}

download()
{
    dl_path="${cwd}"
    dl_url="${1}"
    dl_file="${2:-"${1##*/}"}"

    if [[ "${dl_file}" =~ tar. ]]; then
        output_dir="${dl_file%.*}"
        output_dir="${3:-"${output_dir%.*}"}"
    else
        output_dir="${3:-"${dl_file%.*}"}"
    fi

    target_file="${dl_path}/${dl_file}"
    target_dir="${dl_path}/${output_dir}"

    if [ -f "${target_file}" ]; then
        echo "The file \"${dl_file}\" is already downloaded."
    else
        echo "Downloading \"${dl_url}\" saving as \"${dl_file}\""
        if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
            printf "\n%s\n\n" "The script failed to download \"${dl_file}\" and will try again in 10 seconds..."
            sleep 10
            if ! curl -A "${user_agent}" -Lso "${target_file}" "${dl_url}"; then
                fail_fn "The script failed to download \"${dl_file}\" twice and will now exit:Line ${LINENO}"
            fi
        fi
        echo 'Download Completed'
    fi

    if [ -d "${target_dir}" ]; then
        sudo rm -fr "${target_dir}"
    fi
    mkdir -p "${target_dir}"

    if [ -n "${3}" ]; then
        if ! tar -xf "${target_file}" -C "${target_dir}" 2>/dev/null >/dev/null; then
            sudo rm "${target_file}"
            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script:Line ${LINENO}"
        fi
    else
        if ! tar -xf "${target_file}" -C "${target_dir}" --strip-components 1 2>/dev/null >/dev/null; then
            sudo rm "${target_file}"
            fail_fn "The script failed to extract \"${dl_file}\" so it was deleted. Please re-run the script:Line ${LINENO}"
        fi
    fi

    printf "%s\n\n" "File extracted: ${dl_file}"

    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}:Line ${LINENO}"
}

download_git()
{
    local dl_path dl_url dl_file target_dir

    dl_path="${cwd}"
    dl_url="${1}"
    dl_file="${2:-"${1##*/}"}"
    dl_file="${dl_file//\./-}"
    target_dir="${dl_path}/${dl_file}"

    if [ -n "${3}" ]; then
        output_dir="${dl_path}/${3}"
        target_dir="${output_dir}"
    fi

    if [ -d "${target_dir}" ]; then
        sudo rm -fr "${target_dir}"
    fi

    echo "Downloading ${dl_url} as ${dl_file}"

    if ! git clone -q "${dl_url}" "${target_dir}"; then
        printf "\n%s\n\n" "The script failed to clone the directory \"${target_dir}\" and will try again in 10 seconds..."
        sleep 10
        if ! git clone -q "${dl_url}" "${target_dir}"; then
            fail_fn "The script failed to clone the directory \"${target_dir}\" twice and will now exit the build. Line: ${LINENO}"
        fi
    else
        printf "%s\n\n" "Successfully cloned: ${target_dir}"
    fi

    cd "${target_dir}" || fail_fn "Unable to change the working directory to: ${target_dir}. Line: ${LINENO}"
}

build()
{
    printf "\n%s\n%s\n" \
        "Building ${1} - version ${2}" \
        '===================================='

    if [ -f "${cwd}/${1}.done" ]; then
        if grep -Fx "${2}" "${cwd}/${1}.done" >/dev/null; then
            echo "${1} version ${2} already built. Remove ${cwd}/${1}.done lockfile to rebuild it."
            return 1
        elif "${latest}"; then
            echo "${1} is outdated and will be rebuilt using version ${2}"
            return 0
        else
            echo "${1} is outdated, but will not be rebuilt. Pass in --latest to rebuild it or remove ${cwd}/${1}.done lockfile."
            return 1
        fi
    fi
    return 0
}

build_done() { echo "${2}" > "${cwd}/${1}.done"; }

git_1_fn()
{
    local curl_cmd github_repo github_url g_sver g_sver1

    # SCRAPE GITHUB'S API FOR THE LATEST REPO VERSION
    github_repo="${1}"
    github_url="${2}"

    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://api.github.com/repos/${github_repo}/${github_url}")"; then
        g_sver="$(echo "${curl_cmd}" | jq -r '.[0].tag_name' 2>/dev/null)"
        g_sver1="$(echo "${curl_cmd}" | jq -r '.[0].name' 2>/dev/null)"
        g_ver="${g_sver#v}"
        g_ver1="${g_sver1#v}"
    fi
}

git_2_fn()
{
    gitlab_repo="${1}"
    github_url="${2}"

    if curl_cmd="$(curl -A "${user_agent}" -m 10 -sSL "https://gitlab.kitware.com/api/v4/projects/${gitlab_repo}/repository/${github_url}" | jq -r '.[0].name')"; then
        g_ver="${curl_cmd#v}"
    fi
}

git_ver_fn()
{
    local t_flag u_flag v_flag v_tag v_url

    v_url="${1}"
    v_tag="${2}"

    if [ -n "${3}" ]; then
        v_flag="${3}"
        case "${v_flag}" in
                R)      t_flag=releases;;
                T)      t_flag=tags;;
                *)      fail_fn "Could not detect the variable \"v_flag\". Line: ${LINENO}"
        esac
    fi

    case "${v_tag}" in
            1)      u_flag=git_1_fn;;
            2)      u_flag=git_2_fn;;
            *)      fail_fn "Could not detect the variable \"v_tag\". Line: ${LINENO}"
    esac

    "${u_flag}" "${v_url}" "${t_flag}" 2>/dev/null
}

find_lsb_release="$(sudo find /usr -type f -name 'lsb_release')"

if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS_TMP="$NAME"
    VER_TMP="$VERSION_ID"
    CODENAME="$VERSION_CODENAME"
    OS="$(echo "${OS_TMP}" | awk '{print $1}')"
    VER="$(echo "${VER_TMP}" | awk '{print $1}')"
elif [ -n "${find_lsb_release}" ]; then
    OS="$(lsb_release -d | awk '{print $2}')"
    VER="$(lsb_release -r | awk '{print $2}')"
else
    fail_fn "Failed to define the \$OS and/or \$VER variables. Line: ${LINENO}"
fi

#
# INSTALL REQUIRED APT/PACMAN PACKAGES
#

pkgs_arch_fn()
{
    pkgs_arch=(autoconf automake autogen bluez-qt5 base-devel ccache cmake curl
               git jq libnghttp2 libnghttp3 openssl python python-pip qt5-base
               qt6-base)

    if [ -f /var/lib/pacman/db.lck ]; then
        sudo rm /var/lib/pacman/db.lck
    fi

    for i in ${pkgs_arch[@]}
    do
        missing_pkg="$(sudo pacman -Qi | grep -o "${i}")"

        if [ -z "${missing_pkg}" ]; then
            missing_pkgs+=" ${i}"
        fi
    done

    if [ -n "${missing_pkgs}" ]; then
         sudo pacman -Sq --needed --noconfirm ${missing_pkgs}
    fi

    rm_pip_lock="$(sudo find /usr/lib/python3* -type f -name 'EXTERNALLY-MANAGED')"
    if [ -n "${rm_pip_lock}" ]; then
        sudo rm "${rm_pip_lock}"
    fi

    # INSTALL PYTHON PIP PACKAGES
    pip install -q --user --no-input setuptools wheel
}

pkgs_fn()
{
    pkgs=(autoconf autoconf-archive automake autogen build-essential ccache
          cmake curl jq git libssl-dev libtool libtool-bin m4 python3 python3-pip
          qt6-base-dev)

    for pkg in ${pkgs[@]}
    do
        missing_pkg="$(sudo dpkg -l | grep -o "${pkg}")"

        if [ -z "${missing_pkg}" ]; then
            missing_pkgs+=" ${pkg}"
        fi
    done

    if [ -n "${missing_pkgs}" ]; then
        if ! sudo apt -y install ${missing_pkgs}; then
            sudo killall -9 apt apt-get dpkg
            sudo dpkg --configure -a
            sudo apt --fix-broken install
            sudo apt -f -y install
            sudo apt update
            sudo apt -y install ${missing_pkgs}
        fi
        sudo apt -y autoremove
        clear
    fi
}

case "${OS}" in
    Arch)   pkgs_arch_fn;;
    *)      pkgs_fn;;
esac

#
# INSTALL FROM SOURCE CODE
#

git_ver_fn '541' '2' 'T'
if build 'cmake' "${g_ver}"; then
    download "https://gitlab.kitware.com/cmake/cmake/-/archive/v${g_ver}/cmake-v${g_ver}.tar.bz2" "cmake-${g_ver}.tar.bz2"
    execute ./bootstrap --prefix="${install_dir}"   \
                        --enable-ccache             \
                        --parallel="$(nproc --all)" \
                        --qt-gui
    execute make "-j${cpu_threads}"
    execute sudo make install
    build_done 'cmake' "${g_ver}"
fi

git_ver_fn 'ninja-build/ninja' '1' 'T'
if build 'ninja' "${g_ver1}"; then
    download "https://codeload.github.com/ninja-build/ninja/tar.gz/refs/tags/v${g_ver1}" "ninja-${g_ver1}.tar.gz"
    re2c_path="$(type -P re2c)"
    execute cmake -B build                             \
                  -DCMAKE_install_dir="${install_dir}" \
                  -DCMAKE_BUILD_TYPE=Release           \
                  -DRE2C="${re2c_path}"                \
                  -DBUILD_TESTING=OFF                  \
                  -Wno-dev
    execute make "-j${cpu_threads}" -C build
    execute sudo make -C build install
    build_done 'ninja' "${g_ver1}"
fi

if [[ "${OS}" == 'Arch' ]]; then
    sudo pacman -Sq --needed --noconfirm meson 2>&1
else
    git_ver_fn 'mesonbuild/meson' '1' 'T'
    if build 'meson' "${g_ver1}"; then
        download "https://codeload.github.com/mesonbuild/meson/tar.gz/refs/tags/${g_ver1}" "meson-${g_ver1}.tar.gz"
        execute python3 setup.py build
        execute sudo python3 setup.py install --prefix="${install_dir}"
        build_done 'meson' "${g_ver1}"
    fi
fi

if [[ "${OS}" == 'Arch' ]]; then
    sudo pacman -Sq --needed --noconfirm go 2>&1
    mkdir -p  "${HOME}"/go
    export GOPATH="${HOME}"/go
    source "${HOME}"/.bash_profile
else
    if build 'golang' '1.21.4'; then
        download 'https://go.dev/dl/go1.21.4.linux-amd64.tar.gz' 'golang-1.21.4.tar.gz'
        execute sudo cp -f bin/go bin/gofmt "${install_dir}"/bin
        if [ -d  "${install_dir}"/go ]; then
            sudo rm -fr "${install_dir}"/go
        fi
        sudo mkdir -p "${install_dir}"/go
        GOROOT="${install_dir}"/go
        PATH="${PATH}:${GOROOT}/bin"
        export GOROOT PATH
        build_done 'golang' '1.21.4'
    fi
fi

# LDCONFIG MUST BE RUN NEXT IN ORDER TO UPDATE FILE CHANGES
sudo ldconfig 2>/dev/null

# SHOW THE NEWLY INSTALLED VERSION OF EACH PACKAGE
show_versions_fn

# PROMPT THE USER TO CLEAN UP THE BUILD FILES
cleanup_fn

# SHOW THE EXIT MESSAGE
exit_fn
