#!/Usr/bin/env bash


clear

if [ "$EUID" -eq '0' ]; then
    echo "You must run this script without root or sudo."
    exit 1
fi


script_ver=1.0
jq_ver=1.7
archive_dir="jq-$jq_ver"
archive_url="https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-amd64"
cwd="$PWD"/jq-build-script
install_dir=/usr/local
user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'


if [ -d "$cwd/$archive_dir" ]; then
    sudo rm -fr "$cwd/$archive_dir"
fi
mkdir -p "$cwd/$archive_dir"


if [ ! -f "$cwd/$archive_dir" ]; then
    wget -U "$user_agent" -cq "$archive_url"
fi


printf "\n%s\n%s\n\n"                        \
    "Installing JQ - v$jq_ver" \
    '==============================================='
sleep 2

sudo chmod 755 'jq-linux-amd64'
sudo chown root:root 'jq-linux-amd64'

sudo cp -f 'jq-linux-amd64' "$install_dir"/bin/jq

clear
printf "%s\n\n" "The updated jq file is located at: $(type -P jq)"
jq --version

sudo rm -fr "$cwd"

