#!/usr/bin/env bash

# WHEN INSTALLING OR UPDATING APT PACKAGE MANAGER SOMETIMES CUSTOM SOURCES.LIST MIRROS WILL THROW
# ERRORS STATING THAT THE MIRROR URL IS MISSING IT'S SECURITY GPG KEY. THIS SCRIPT WILL QUICKLY HELP
# YOU TO FIX THOSE ERRORS. JUST COPY THE KEY NAMES FROM THE TERMINAL AND PLACE THEM INSIDE THE KEYS
# FUNCTION BELOW AND SEPARATE EACH KEY WITH A SINGLE SPACE. THEN RUN THIS SCRIPT USING THE SUDO BASH
# COMMAND

if [ "$EUID" -ne 0 ]; then
    echo "You must run this script with root or sudo."
    exit 1
fi

keys=(112695A0E562B32A 54404762BBB6E853)

for key in ${keys[@]}; do
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv ${key}
done
