#!/usr/bin/env bash

url="https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/misc/source-git-repo-version.sh"
user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36'

# Finish the download before executing it so a failed transfer cannot run a partial script.
if ! helper=$(curl -q --fail --silent --show-error --location \
    --proto '=https' --proto-redir '=https' --connect-timeout 10 --max-time 30 \
    --max-redirs 5 --retry 2 --retry-max-time 30 --user-agent "$user_agent" "$url"); then
    printf 'git-repo-test.sh: Could not download the version helper.\n' >&2
    exit 1
fi
if [[ -z $helper ]]; then
    printf 'git-repo-test.sh: The downloaded version helper is empty.\n' >&2
    exit 1
fi

echo -n "ansible: "
bash -s -- "https://github.com/ansible/ansible.git" <<< "$helper"
echo -n "beats: "
bash -s -- "https://github.com/elastic/beats.git" <<< "$helper"
echo -n "cassandra: "
bash -s -- "https://github.com/apache/cassandra.git" <<< "$helper"
echo -n "chef: "
bash -s -- "https://github.com/chef/chef.git" <<< "$helper"
echo -n "consul: "
bash -s -- "https://github.com/consul/consul.git" <<< "$helper"
echo -n "cpython: "
bash -s -- "https://github.com/python/cpython.git" <<< "$helper"
echo -n "curl: "
bash -s -- "https://github.com/curl/curl.git" <<< "$helper"
echo -n "docker-ce: "
bash -s -- "https://github.com/docker/docker-ce.git" <<< "$helper"
echo -n "drill: "
bash -s -- "https://github.com/apache/drill.git" <<< "$helper"
echo -n "elasticsearch: "
bash -s -- "https://github.com/elastic/elasticsearch.git" <<< "$helper"
echo -n "flink: "
bash -s -- "https://github.com/apache/flink.git" <<< "$helper"
echo -n "gcc: "
bash -s -- "https://github.com/gcc-mirror/gcc.git" <<< "$helper"
echo -n "git: "
bash -s -- "https://github.com/git/git.git" <<< "$helper"
echo -n "go: "
bash -s -- "https://github.com/golang/go.git" <<< "$helper"
echo -n "grafana: "
bash -s -- "https://github.com/grafana/grafana.git" <<< "$helper"
echo -n "hadoop: "
bash -s -- "https://github.com/apache/hadoop.git" <<< "$helper"
echo -n "hbase: "
bash -s -- "https://github.com/apache/hbase.git" <<< "$helper"
echo -n "hive: "
bash -s -- "https://github.com/apache/hive.git" <<< "$helper"
echo -n "httpd: "
bash -s -- "https://github.com/apache/httpd.git" <<< "$helper"
echo -n "influxdb: "
bash -s -- "https://github.com/influxdata/influxdb.git" <<< "$helper"
echo -n "kafka: "
bash -s -- "https://github.com/apache/kafka.git" <<< "$helper"
echo -n "kubernetes: "
bash -s -- "https://github.com/kubernetes/kubernetes.git" <<< "$helper"
echo -n "libpng: "
bash -s -- "https://github.com/pnggroup/libpng.git" <<< "$helper"
echo -n "linux: "
bash -s -- "https://github.com/torvalds/linux.git" <<< "$helper"
echo -n "llvm: "
bash -s -- "https://github.com/llvm/llvm-project.git" <<< "$helper"
echo -n "logstash: "
bash -s -- "https://github.com/elastic/logstash.git" <<< "$helper"
echo -n "lucene: "
bash -s -- "https://github.com/apache/lucene.git" <<< "$helper"
echo -n "moby: "
bash -s -- "https://github.com/moby/moby.git" <<< "$helper"
echo -n "mongodb: "
bash -s -- "https://github.com/mongodb/mongo.git" <<< "$helper"
echo -n "nginx: "
bash -s -- "https://github.com/nginx/nginx.git" <<< "$helper"
echo -n "nifi: "
bash -s -- "https://github.com/apache/nifi.git" <<< "$helper"
echo -n "node: "
bash -s -- "https://github.com/nodejs/node.git" <<< "$helper"
echo -n "openssl: "
bash -s -- "https://github.com/openssl/openssl.git" <<< "$helper"
echo -n "php: "
bash -s -- "https://github.com/php/php-src.git" <<< "$helper"
echo -n "postgres: "
bash -s -- "https://github.com/postgres/postgres.git" <<< "$helper"
echo -n "prometheus: "
bash -s -- "https://github.com/prometheus/prometheus.git" <<< "$helper"
echo -n "puppet: "
bash -s -- "https://github.com/puppetlabs/puppet.git" <<< "$helper"
echo -n "redis: "
bash -s -- "https://github.com/redis/redis.git" <<< "$helper"
echo -n "ruby: "
bash -s -- "https://github.com/ruby/ruby.git" <<< "$helper"
echo -n "rust: "
bash -s -- "https://github.com/rust-lang/rust.git" <<< "$helper"
echo -n "salt: "
bash -s -- "https://github.com/saltstack/salt.git" <<< "$helper"
echo -n "spark: "
bash -s -- "https://github.com/apache/spark.git" <<< "$helper"
echo -n "sqlite: "
bash -s -- "https://github.com/sqlite/sqlite.git" <<< "$helper"
echo -n "terraform-provider-aws: "
bash -s -- "https://github.com/terraform-providers/terraform-provider-aws.git" <<< "$helper"
echo -n "vault: "
bash -s -- "https://github.com/hashicorp/vault.git" <<< "$helper"
echo -n "vim: "
bash -s -- "https://github.com/vim/vim.git" <<< "$helper"
echo -n "zookeeper: "
bash -s -- "https://github.com/apache/zookeeper.git" <<< "$helper"
