#!/usr/bin/env bash

url="https://raw.githubusercontent.com/slyfox1186/script-repo/main/Bash/Misc/source-git-repo-version.sh"

echo -n "ansible: "
curl -fsS "$url" | bash -s "https://github.com/ansible/ansible.git"
echo -n "beats: "
curl -fsS "$url" | bash -s "https://github.com/elastic/beats.git"
echo -n "cassandra: "
curl -fsS "$url" | bash -s "https://github.com/apache/cassandra.git"
echo -n "chef: "
curl -fsS "$url" | bash -s "https://github.com/chef/chef.git"
echo -n "consul: "
curl -fsS "$url" | bash -s "https://github.com/consul/consul.git"
echo -n "cpython: "
curl -fsS "$url" | bash -s "https://github.com/python/cpython.git"
echo -n "curl: "
curl -fsS "$url" | bash -s "https://github.com/curl/curl.git"
echo -n "docker-ce: "
curl -fsS "$url" | bash -s "https://github.com/docker/docker-ce.git"
echo -n "drill: "
curl -fsS "$url" | bash -s "https://github.com/apache/drill.git"
echo -n "elasticsearch: "
curl -fsS "$url" | bash -s "https://github.com/elastic/elasticsearch.git"
echo -n "flink: "
curl -fsS "$url" | bash -s "https://github.com/apache/flink.git"
echo -n "gcc: "
curl -fsS "$url" | bash -s "https://github.com/gcc-mirror/gcc.git"
echo -n "git: "
curl -fsS "$url" | bash -s "https://github.com/git/git.git"
echo -n "go: "
curl -fsS "$url" | bash -s "https://github.com/golang/go.git"
echo -n "grafana: "
curl -fsS "$url" | bash -s "https://github.com/grafana/grafana.git"
echo -n "hadoop: "
curl -fsS "$url" | bash -s "https://github.com/apache/hadoop.git"
echo -n "hbase: "
curl -fsS "$url" | bash -s "https://github.com/apache/hbase.git"
echo -n "hive: "
curl -fsS "$url" | bash -s "https://github.com/apache/hive.git"
echo -n "httpd: "
curl -fsS "$url" | bash -s "https://github.com/apache/httpd.git"
echo -n "influxdb: "
curl -fsS "$url" | bash -s "https://github.com/influxdata/influxdb.git"
echo -n "kafka: "
curl -fsS "$url" | bash -s "https://github.com/apache/kafka.git"
echo -n "kubernetes: "
curl -fsS "$url" | bash -s "https://github.com/kubernetes/kubernetes.git"
echo -n "libpng: "
curl -fsS "$url" | bash -s "https://github.com/pnggroup/libpng.git"
echo -n "linux: "
curl -fsS "$url" | bash -s "https://github.com/torvalds/linux.git"
echo -n "llvm: "
curl -fsS "$url" | bash -s "https://github.com/llvm/llvm-project.git"
echo -n "logstash: "
curl -fsS "$url" | bash -s "https://github.com/elastic/logstash.git"
echo -n "lucene: "
curl -fsS "$url" | bash -s "https://github.com/apache/lucene.git"
echo -n "moby: "
curl -fsS "$url" | bash -s "https://github.com/moby/moby.git"
echo -n "mongodb: "
curl -fsS "$url" | bash -s "https://github.com/mongodb/mongo.git"
echo -n "nginx: "
curl -fsS "$url" | bash -s "https://github.com/nginx/nginx.git"
echo -n "nifi: "
curl -fsS "$url" | bash -s "https://github.com/apache/nifi.git"
echo -n "node: "
curl -fsS "$url" | bash -s "https://github.com/nodejs/node.git"
echo -n "openssl: "
curl -fsS "$url" | bash -s "https://github.com/openssl/openssl.git"
echo -n "php: "
curl -fsS "$url" | bash -s "https://github.com/php/php-src.git"
echo -n "postgres: "
curl -fsS "$url" | bash -s "https://github.com/postgres/postgres.git"
echo -n "prometheus: "
curl -fsS "$url" | bash -s "https://github.com/prometheus/prometheus.git"
echo -n "puppet: "
curl -fsS "$url" | bash -s "https://github.com/puppetlabs/puppet.git"
echo -n "redis: "
curl -fsS "$url" | bash -s "https://github.com/redis/redis.git"
echo -n "ruby: "
curl -fsS "$url" | bash -s "https://github.com/ruby/ruby.git"
echo -n "rust: "
curl -fsS "$url" | bash -s "https://github.com/rust-lang/rust.git"
echo -n "salt: "
curl -fsS "$url" | bash -s "https://github.com/saltstack/salt.git"
echo -n "spark: "
curl -fsS "$url" | bash -s "https://github.com/apache/spark.git"
echo -n "sqlite: "
curl -fsS "$url" | bash -s "https://github.com/sqlite/sqlite.git"
echo -n "terraform-provider-aws: "
curl -fsS "$url" | bash -s "https://github.com/terraform-providers/terraform-provider-aws.git"
echo -n "vault: "
curl -fsS "$url" | bash -s "https://github.com/hashicorp/vault.git"
echo -n "vim: "
curl -fsS "$url" | bash -s "https://github.com/vim/vim.git"
echo -n "zookeeper: "
curl -fsS "$url" | bash -s "https://github.com/apache/zookeeper.git"
