#!/bin/bash
# Editor-related aliases

# Nano editor shortcuts
alias nba='nano ~/.bash_aliases; cl'
alias nbf='nano ~/.bash_functions; cl'
alias nbrc='nano ~/.bashrc; cl'
alias npro='nano ~/.profile; cl'
alias napt='sudo nano /etc/apt/apt.conf; cl'
alias ncron='sudo nano /etc/crontab; cl'
alias nddc='sudo nano /etc/ddclient.conf; cl'
alias nhosts='sudo nano /etc/hosts; cl'
alias nlist='sudo nano /etc/apt/sources.list; cl'
alias nlogin='sudo nano /etc/gdm*/daemon.conf; cl'
alias nnano='sudo nano /etc/nanorc; cl'
alias nnet='sudo nano /etc/network/interfaces; cl'
alias nssh='sudo nano /etc/ssh/sshd_config; cl'
alias nsudo='sudo nano /etc/sudoers; cl'
alias nlang='sudo nano /usr/share/gtksourceview-*/language-specs/sh.lang; cl'
alias crontab='crontab -e'

# Gnome text editor shortcuts
alias gba='gnome-text-editor ~/.bash_aliases; cl'
alias gbf='gnome-text-editor ~/.bash_functions; cl'
alias gbrc='gnome-text-editor ~/.bashrc; cl'
alias gpro='gnome-text-editor ~/.profile; cl'
alias g='gnome-text-editor'
alias gapt='sudo gnome-text-editor /etc/apt/apt.conf; cl'
alias gcron='sudo gnome-text-editor /etc/crontab; cl'
alias gddc='sudo gnome-text-editor /etc/ddclient.conf; cl'
alias ghosts='sudo gnome-text-editor /etc/hosts; cl'
alias glist='sudo gnome-text-editor /etc/apt/sources.list; cl'
alias glogin='sudo gnome-text-editor /etc/gdm*/daemon.conf; cl'
alias ggnome-text-editor='sudo gnome-text-editor /etc/gnome-text-editorrc; cl'
alias gnet='sudo gnome-text-editor /etc/network/interfaces; cl'
alias gssh='sudo gnome-text-editor /etc/ssh/sshd_config; cl'
alias gsudo='sudo gnome-text-editor /etc/sudoers; cl'
alias glang='sudo gnome-text-editor /usr/share/gtksourceview-*/language-specs/sh.lang; cl'

# Cat command shortcuts
alias cba='cat ~/.bash_aliases; cl'
alias cbf='cat ~/.bash_functions; cl'
alias cbrc='cat ~/.bashrc; cl'
alias cpro='cat ~/.profile; cl'
alias capt='clear; cat /etc/apt/sources.list'
alias cbasrc='clear; cat /etc/bash.bashrc'
alias ccat='clear; cat /etc/catrc'
alias ccron='clear; cat /etc/crontab'
alias cddc='clear; cat /etc/ddclient.conf'
alias chosts='clear; cat /etc/hosts'
alias clangs='clear; cat /usr/share/gtksourceview-*/language-specs/sh.lang'
alias clist='clear; cat /etc/apt/sources.list'
alias clogin='clear; cat /etc/gdm*/daemon.conf'
alias cnano='clear; cat /etc/nanorc'
alias cnet='clear; cat /etc/network/interfaces'
alias cssh='clear; cat /etc/ssh/sshd_config'
alias csudo='clear; cat /etc/sudoers'