#!/usr/bin/env bash
# Editor-related aliases

# Nano editor shortcuts
alias nba='nano ~/.bash_aliases; cl'
alias nbf='nano ~/.bash_functions; cl'
alias nbrc='nano ~/.bashrc; cl'
alias npro='nano ~/.profile; cl'
alias npac='sudo nano /etc/pacman.conf; cl'
alias ncron='sudo nano /etc/crontab; cl'
alias nddc='sudo nano /etc/ddclient.conf; cl'
alias nhosts='sudo nano /etc/hosts; cl'
alias nmirror='sudo nano /etc/pacman.d/mirrorlist; cl'
alias nlogin='sudo nano /etc/gdm*/daemon.conf; cl'
alias nnano='sudo nano /etc/nanorc; cl'
alias nnet='sudo nano /etc/systemd/network/; cl'
alias nssh='sudo nano /etc/ssh/sshd_config; cl'
alias nsudo='sudo nano /etc/sudoers; cl'
alias nlang='sudo nano /usr/share/gtksourceview-*/language-specs/sh.lang; cl'
alias crontab='crontab -e'

# Gnome text editor shortcuts
alias gba='gnome-text-editor ~/.bash_aliases; cl'
alias gbf='gnome-text-editor ~/.bash_functions; cl'
alias gbrc='gnome-text-editor ~/.bashrc; cl'
alias gpro='gnome-text-editor ~/.profile; cl'
alias g='gnome-text-editor'
alias gpac='sudo gnome-text-editor /etc/pacman.conf; cl'
alias gcron='sudo gnome-text-editor /etc/crontab; cl'
alias gddc='sudo gnome-text-editor /etc/ddclient.conf; cl'
alias ghosts='sudo gnome-text-editor /etc/hosts; cl'
alias gmirror='sudo gnome-text-editor /etc/pacman.d/mirrorlist; cl'
alias glogin='sudo gnome-text-editor /etc/gdm*/daemon.conf; cl'
alias ggnome-text-editor='sudo gnome-text-editor /etc/gnome-text-editorrc; cl'
alias gnet='sudo gnome-text-editor /etc/systemd/network/; cl'
alias gssh='sudo gnome-text-editor /etc/ssh/sshd_config; cl'
alias gsudo='sudo gnome-text-editor /etc/sudoers; cl'
alias glang='sudo gnome-text-editor /usr/share/gtksourceview-*/language-specs/sh.lang; cl'

# Cat command shortcuts
alias cba='cat ~/.bash_aliases; cl'
alias cbf='cat ~/.bash_functions; cl'
alias cbrc='cat ~/.bashrc; cl'
alias cpro='cat ~/.profile; cl'
alias cpac='clear; cat /etc/pacman.conf'
alias cbasrc='clear; cat /etc/bash.bashrc'
alias ccat='clear; cat /etc/catrc'
alias ccron='clear; cat /etc/crontab'
alias cddc='clear; cat /etc/ddclient.conf'
alias chosts='clear; cat /etc/hosts'
alias clangs='clear; cat /usr/share/gtksourceview-*/language-specs/sh.lang'
alias cmirror='clear; cat /etc/pacman.d/mirrorlist'
alias clogin='clear; cat /etc/gdm*/daemon.conf'
alias cnano='clear; cat /etc/nanorc'
# alias cssh='clear; cat /etc/ssh/sshd_config'
alias csudo='clear; cat /etc/sudoers'
