#!/bin/bash

clear

#
# ARIA2 INSTALLER SCRIPT
#

script_ver=1.0
archive_dir=aria2-1.36.0
archive_url=https://github.com/aria2/aria2/releases/download/release-1.36.0/aria2-1.36.0.tar.gz
archive_ext="${archive_url//*.}"
cwd="$PWD"/aria2-build-script

printf "\n%s\n%s\n\n" \
    "Aria2 Build Script - v$script_ver" \
    '==============================================='

#
# CREATE OUTPUT DIRECTORY
#

mkdir -p "$cwd"

#
# SET THE C+CPP COMPILERS
#

export CC=gcc CXX=g++

#
# CREATE FUNCTIONS
#

exit_fn()
{
    printf "\n%s\n\n" 'The script has completed.'
    exit 0
}


fail_fn()
{
    printf "%s\n\n" "$1"
    exit 1
}

cleanup_fn()
{
    local choice

    if [ -f /usr/bin/aria2c ]; then
        sudo apt -y remove aria2
    fi

    printf "\n%s\n%s\n%s\n\n%s\n%s\n\n" \
        '============================================' \
        '  Do you want to clean up the build files?  ' \
        '============================================' \
        '[1] Yes' \
        '[2] No'
    read -p 'Your choices are (1 or 2): ' choice

    case "$choice" in
        1)      sudo rm -fr "$cwd";;
        2)      echo;;
        *)
                clear
                printf "%s\n\n" 'Bad user input. Reverting script...'
                sleep 3
                unset choice
                clear
                cleanup_fn
                ;;
    esac
}

link_fn()
{
    if [ -f "/usr/local/bin/$pc_type-aria2c" ]; then
        sudo ln -sf "/usr/local/bin/$pc_type-aria2c" /usr/local/bin/aria2c
    fi
}

#
# INSTALL REQUIRED APT cwd
#

pkgs=(autoconf autogen automake build-essential ca-certificates ccache clang curl libaria2-0 libaria2-0-dev
      libc-ares-dev libdmalloc-dev libgcrypt20-dev libgmp-dev libgnutls28-dev libgpg-error-dev libjemalloc-dev
      libmbedtls-dev libnghttp2-dev librust-openssl-dev libsqlite3-dev libssh2-1-dev libssh-dev libssl-dev
      libxml2-dev pkg-config zlib1g-dev)

for i in ${pkgs[@]}
do
    missing_pkg="$(dpkg -l | grep $i)"

    if [ -z "$missing_pkg" ]; then
        missing_pkgs+=" $i"
    fi
done
unset i

if [ -n "$missing_pkgs" ]; then
    sudo apt -y install $missing_pkgs
    clear
fi

#
# GET PC TYPE
#

curl -Lso "$cwd/config.guess" 'https://raw.githubusercontent.com/gcc-mirror/gcc/master/config.guess'
chmod +x "$cwd/config.guess"
pc_type="$(source "$cwd/config.guess")"

#
# DOWNLOAD ARCHIVE FILE
#

archive_name="$archive_dir.tar.$archive_ext"

if [ ! -f "$cwd/$archive_name" ]; then
    curl -Lso "$cwd/$archive_name" "$archive_url"
fi

#
# CREATE OUTPUT DIRECTORY
#

if [ -d "$cwd/$archive_dir" ]; then
    sudo rm -fr "$cwd/$archive_dir"
fi
mkdir -p "$cwd/$archive_dir/build"

#
# EXTRACT ARCHIVE FILES
#

if ! tar -xf "$cwd/$archive_name" -C "$cwd/$archive_dir" --strip-components 1; then
    printf "%s\n\n" "Failed to extract: $cwd/$archive_name"
    exit 1
fi

#
# REMOVE APT VERSION OF ARAI2 IF IT IS INSTALLED
#

if [ -f /usr/bin/aria2c ]; then
    sudo apt -y remove aria2
fi

#
# BUILD PROGRAM FROM SOURCE
#

cd "$cwd/$archive_dir" || exit 1
# INCREASE THE MAX NUMBER OF CONNECTIONS FROM 16 TO 128
sed -i 's/1, 16/1, 128/g' src/OptionHandlerFactory.cc
cd build || exit 1
../configure --prefix=/usr/local              \
             --{build,host,target}="$pc_type" \
             --disable-nls                    \
             --disable-shared                 \
             --disable-werror                 \
             --enable-libaria2                \
             --enable-static                  \
             --with-ca-bundle="$pem_target"   \
             --with-libgcrypt                 \
             --with-libuv                     \
             --with-jemalloc                  \
             --with-openssl                   \
             --without-gnutls                 \
             --without-libnettle
make "-j$(nproc --all)"
if ! sudo make install; then
    make distclean
    printf "\n%s\n\n" 'Failed to install aria2.'
    exit 1
fi

# CREATE SOFT LINK
link_fn
# CLEANUP BUILD FILES
cleanup_fn
# SHOW EXIT MESSAGE
exit_fn
