#!/usr/bin/env sh

echo

sudo rm /usr/bin/tilix 2>/dev/null
sudo rm /usr/share/glib-2.0/schemas/com.gexperts.Tilix.gschema.xml 2>/dev/null
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/ 2>/dev/null
sudo rm -rf /usr/share/tilix 2>/dev/null

sudo find /usr/share/locale -type f -name "tilix.mo" -delete 2>/dev/null
sudo find /usr/share/icons/hicolor -type f -name "com.gexperts.Tilix.png" -delete 2>/dev/null
sudo find /usr/share/icons/hicolor -type f -name "com.gexperts.Tilix*.svg" -delete 2>/dev/null
sudo rm /usr/share/nautilus-python/extensions/open-tilix.py 2>/dev/null
sudo rm /usr/share/dbus-1/services/com.gexperts.Tilix.service 2>/dev/null
sudo rm /usr/share/applications/com.gexperts.Tilix.desktop 2>/dev/null
sudo rm /usr/share/metainfo/com.gexperts.Tilix.appdata.xml 2>/dev/null
sudo rm /usr/share/man/man1/tilix.1.gz 2>/dev/null
sudo rm /usr/share/man/*/man1/tilix.1.gz 2>/dev/null

## REMOVE HOME DIRECTORY ENTRIES
if [ -d "$HOME"/.config/tilix ]; then
    sudo rm -r "$HOME"/.config/tilix
fi

sudo rm -fr "$tilix_schemes"/*.json

printf "%s\n\n" \
    'Tilix has been removed.'
